### ISSUE TITLE
Unexpected behavior in RepositoryMining

### ISSUE THREAD

**Issue by stefanodallapalma** [ishepard/pydriller#103]
In the repository```DataDog/ansible-datadog```, the commit ```edf7f39adb5301c6d157cbc07291cc5cd6629dc2``` [precedes](https://github.com/DataDog/ansible-datadog/commits?after=62361a908eb821af75a1440cb215f857a1e9340b+150) ```5adf2f1659fb8686b27317aa7ee2f6468bbcdb38``` (in chronological order).

While running:

```
for commit in RepositoryMining('https://github.com/DataDog/ansible-datadog', from_commit='edf7f39adb5301c6d157cbc07291cc5cd6629dc2', to_commit='5adf2f1659fb8686b27317aa7ee2f6468bbcdb38').traverse_commits():
    print(commit.hash)
```

I expect

```
edf7f39adb5301c6d157cbc07291cc5cd6629dc2
5adf2f1659fb8686b27317aa7ee2f6468bbcdb38
```

but obtain 
```
(nothing)
```

The expected result is obtained by swapping  ```from_commit``` and ```to_commit```.
This is a bit misleading.

**PyDriller version:** Latest commit ->  ```dc5d544ff1d0aac23e4cbd1b14a179b04323defb```

**Comment by ishepard** [comment]
Hi @stefanodallapalma!
Thanks for catching this. This is definitely wrong, I will have a look at it now.
