### ISSUE TITLE
traverse_files()

### ISSUE THREAD

**Issue by ishepard** [ishepard/pydriller#11]
One user asked to implement a traverse_file() function instead of traverse_commits().

In this case, I would have to obtain the list of files of the repo in that specific moment, and trace back all the commits in which each file was modified.

The result will be a dictionary, in which the keys are the files, and the value for each key is a list of commits.

**Comment by Marlysson** [comment]
Will this be the more direct action instead of run traverse_commits() and create a dictionary of commit.modifications's content?

**Comment by ishepard** [comment]
The disadvantage of your approach is that it would collect information about *ALL* the files ever committed. What the user wants instead is only the information regarding the files in the system NOW.
