### ISSUE TITLE
Newer versions of PyDriller (> 1.7) create git lock removing support for parallelised mining.

### ISSUE THREAD

**Issue by gotec** [ishepard/pydriller#110]
Hi Davide,
In our tool [git2net](https://github.com/gotec/git2net), we use PyDriller to interface with the git repositories that we mine mine co-editing relationships from. As this process is very time consuming, we have a parallel implementation that allows us to independently analyse different commits on multiple cores. This has worked great up to PyDriller 1.7.

**Describe the bug**
It seems that with some version > 1.7, you have introduced a lock for the git repository that prohibits parallel access. I now receive an `OSError: Lock for file 'path_to_repo/.git/config' did already exist, delete 'path_to_repo/.git/config.lock' in case the lock is illegal`.

Is there a flag such that the lock is not set and parallel processing is still possible? Unfortunately, sticking to PyDriller 1.7 is not an option, as newer versions of PyDriller fix some issues with diffs that are essential to my research.

**To Reproduce**
Run
```
import git2net
import os

def test_mine_git_repo(repo_string, sqlite_db_file):
    if os.path.exists(sqlite_db_file):
        os.remove(sqlite_db_file)
    git2net.mine_git_repo(repo_string, sqlite_db_file, blame_C='CCC4')
    assert True

test_mine_git_repo('test_repo', 'out.db')
```
for the test repository for [git2net](https://github.com/gotec/git2net/tree/master/test_repos) with PyDriller 1.13 (You will need to remove the version specification in `requirements.txt`).

It runs fine in sequential mode, i.e.
```
def test_mine_git_repo_sequential(repo_string, sqlite_db_file):
    if os.path.exists(sqlite_db_file):
        os.remove(sqlite_db_file)
    git2net.mine_git_repo(repo_string, sqlite_db_file, blame_C='CCC4', no_of_processes=1)
    assert True
```

**OS Version:**
 Ubuntu 19.10

Thanks a lot for your support!
Cheers,
Christoph

**Comment by marco-c** [comment]
One way to work around the problem is:
```
    thread_local = threading.local()
    git_init_lock = threading.Lock()

    def _init(git_repo_dir):
        with git_init_lock:
            thread_local.git = GitRepository(git_repo_dir)
            # Call get_head in order to make pydriller initialize the repository.
            thread_local.git.get_head()

    def whatever():
        thread_local.git.DO_WHAT_YOU_WANT

    with concurrent.futures.ThreadPoolExecutor(initializer=_init, initargs=(repo_dir,)) as executor:
        executor.submit(whatever)
```

**Comment by marco-c** [comment]
I believe the issue comes from writing to the repository configuration in https://github.com/ishepard/pydriller/blob/32f744a697927d9b856164e221ac534801d1bdee/pydriller/git_repository.py#L99.
Possibly, pydriller could implement the locking by itself. Or easier, it could open the repository and write the config in the constructor of GitRepository directly (mentioning in the documentation that opening a repository is not thread-safe).

**Comment by gotec** [comment]
Hi Marco,

I have implemented the work around you described and it seems to have done the trick.

Thanks a lot for your quick response!

Cheers,
Christoph

**Comment by gotec** [comment]
Maybe I have celebrated to early here. While the tests are running fine, I still get errors from some workers when running outside of pytest. My implementation now looks as follows:

```
def _init(git_repo_dir):
    with git_init_lock:
        thread_local.git = pydriller.GitRepository(git_repo_dir)
        # Call get_head in order to make pydriller initialise the repositry.
        thread_local.git.get_head()

with multiprocessing.Pool(no_of_processes, initializer=_init, initargs=(repo_string,)) as p:
    for result in p.imap_unordered(_process_commit, args, chunksize=chunksize):
            ...
``` 
`thread_local` and `git_init_lock` are defined globally, as is `_process_commit`.

The only difference I see is the use of `multiprocessing.Pool` instead of `concurrent.futures.ThreadPoolExecutor`. Could that be an issue?

**Comment by marco-c** [comment]
Yeah, my example applies when you use multiple threads. If you use multiple processes, you will need to use a multiprocessing lock instead of a threading lock, and you don't need a thread local variable, you can just use a global that you initialize in _init_process (in the multithreading case, the global would be shared between threads, so that wouldn't work; in the multiprocessing case, each process gets its own global).
Something like this *should* work:
```
git_init_lock = multiprocessing.Lock()

def _init_process(git_repo_dir):
    global git
    with git_init_lock:
        git = pydriller.GitRepository(git_repo_dir)
        # Call get_head in order to make pydriller initialise the repositry.
        git.get_head()
```

**Comment by gotec** [comment]
Finally got it to run. For some reason, the lock does not seem to work when used in the ititialiser. Similar to [the setup shown here](https://stackoverflow.com/questions/28664720/how-to-create-global-lock-semaphore-with-multiprocessing-pool-in-python), I now only using the initialisation to pass the lock to the process and initialise the PyDriller GitRepository object there. This seems to work so far.

Thanks again for your help!
Cheers,
Christoph
