### ISSUE TITLE
Consider using rust-code-analysis instead of (or in addition to) Lizard

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#114]
You might be interested in taking a look at https://github.com/mozilla/rust-code-analysis, it supports fewer languages than Lizard, but probably in a better way (especially C/C++).

**Comment by ishepard** [comment]
thanks for sharing it @marco-c! I love it, it seems very cool!
Any way there is gonna be some kind of API in Python? 
Lyzard is wonderful because I can add it as package in the requirements and call it directly from the python code..I guess I would have to spawn a process and parse the result in the case of rust-code-analysis?

**Comment by marco-c** [comment]
At the moment, I'm using it through a REST API (see https://github.com/mozilla/bugbug/blob/a1111e5d55ec8001ad23a0fdadc38c9cd7a2c84a/bugbug/rust_code_analysis_server.py#L67), but we could possibly create a Python library to use it (https://github.com/mozilla/rust-code-analysis/issues/54).

**Comment by ishepard** [comment]
Indeed, I think it could be a nice addition!
If I have time I could also work on it. We create a new library `py-code-analysis`, that internally uses rust-code-analysis (through REST APIs or parsing the output, whatever is the easiest one).
If you like this option we could start that package together. 

Do you have any information on the performance of the tool?

**Comment by marco-c** [comment]
I'd say we have two options:
- create a library which takes care of downloading the rust-code-analysis binary for the OS you're running on and uses the REST API (or the CLI interface) to execute it;
- create a native Python library as a wrapper of rust-code-analysis using PyO3 (a bit like https://github.com/mozilla/pyo3-parsepatch for https://github.com/mozilla/rust-parsepatch; another example is https://github.com/ijl/orjson).

The second option would be better performance-wise, but requires a bit more work (and mostly in Rust).
CC @calixteman, if you have any opinion.

**Comment by ishepard** [comment]
Closing this issue, everyone feel free to re-open it if you feel like working on it.

**Comment by marco-c** [comment]
> Closing this issue, everyone feel free to re-open it if you feel like working on it.

I'd love to do this, I wish I had time :(
@Luni-4 would you be interested?

**Comment by Luni-4** [comment]
It would be a good addition for `rust-code-analysis` but I don't have time to do that. 

Perhaps someone could use `PyO3` to wrap the `Rust` APIs in Python
