### ISSUE TITLE
Get only Modified Methods

### ISSUE THREAD

**Issue by razi-rechan** [ishepard/pydriller#118]
I understand that methods in modifications contains all methods belongs to the modified class. Is this possible to get only modified methods please?

**Comment by ishepard** [comment]
Hi @razi-rechan,
yes it is possible, it's called `changed_methods` (inside Modification of course).

**Comment by razi-rechan** [comment]
I could not find changed_methods in Modification. Here is my code:

**Comment by razi-rechan** [comment]
dt1 = datetime.datetime(2002, 4, 1)
dt2 = datetime.datetime(2010, 5, 1)
gr = GitRepository('C:/Users/abdul.razzaq.UL/git/eclipse.platform.swt/.git')
for commit in RepositoryMining('C:/Users/abdul.razzaq.UL/git/eclipse.platform.swt/.git', since=dt1, to=dt2, only_modifications_with_file_types=['.java']).traverse_commits():
    if(commit.merge):
        for mod in commit.modifications:
            print(mod.changed_methods)

**Comment by ishepard** [comment]
that is because you are only analyzing merge commits.
The current behaviour of Pydriller is to **not** return modifications of merge commits, since we can not parse those yet.

For reference, see 
https://github.com/ishepard/pydriller/issues/109#issuecomment-603213851
https://github.com/ishepard/pydriller/issues/89#issuecomment-590243707

**Comment by razi-rechan** [comment]
Even i remove that still there is no method/property named changed_methods in Modification, there is a property changed_type but not changed_methods

**Comment by ishepard** [comment]
What version of Pydriller are you running?
The property is [here](https://github.com/ishepard/pydriller/blob/cc0c53cf881f5cd03ee4640798b99afbff67e474/pydriller/domain/commit.py#L344) and it was introduced in Pydriller 1.12

**Comment by razi-rechan** [comment]
I am using 1.14, I installed in PyCharm

**Comment by ishepard** [comment]
Mmmmm that is really strange.
The property is there and there are tests as well that call it. 
Can you check the implementation of the `Modification` object on your local environment and see what's there? You can do it in Pycharm, just click on `mod` and see the code. It should be the same of [this](https://github.com/ishepard/pydriller/blob/cc0c53cf881f5cd03ee4640798b99afbff67e474/pydriller/domain/commit.py#L136), and it should contain `changed_methods`.

**Comment by razi-rechan** [comment]
I got, two PyDriller were installed. Thanks for your help

**Comment by ishepard** [comment]
You’re welcome! Cheers

**Comment by gurubhandari** [comment]
Have you calculated the fan_in and fan_out of the methods correctly? I am getting fan_in and fan_out all zeros for all the methods.

**Comment by cp3-three** [comment]
> Have you calculated the fan_in and fan_out of the methods correctly? I am getting fan_in and fan_out all zeros for all the methods.

I get same question,  had you resolved it?

**Comment by gurubhandari** [comment]
Hi,

I couldn't solve the problem since it was not correctly classifying with
pydriller and not even with the original API gitgub which is used in
pydriller.
Did you get any update? I have not followed it so far.

Regards,
Guru
