### ISSUE TITLE
RepositoryMining: 'reverse' is not the default order

### ISSUE THREAD

**Issue by jakob-ed** [ishepard/pydriller#125]
**Describe the bug**
The documentation for `RepositoryMining` states that the `order` parameter defaults to `reverse`. However, this seems to not be the case:

- If I set `order='reverse'`, the **newest** commit is yielded first by the `traverse_commits()` generator.
- If I don't specify `order`, the **oldest** commit is yielded first by the `traverse_commits()` generator. 

I would expect both alternatives (setting `order='reverse'` and not setting `order`) to behave the same way (returning the commits in the same order when calling `traverse_commits`)

**To Reproduce**

```
for commit in RepositoryMining('path/to/repo').traverse_commits():
    print(commit.hash)  # returns oldest commit first
    break

for commit in RepositoryMining('path/to/repo', order='reverse').traverse_commits():
    print(commit.hash)  # returns newest commit first
    break
```

**OS Version:**
MacOS

**Comment by ishepard** [comment]
Hi @jakob-ed!
So, by default Pydriller returns the commits from the oldest to the newest.
If you need viceversa, you should use `order='reverse'`.
I will update the documentation and clarify this! Thank you

**Comment by maldil** [comment]
@ishepard I experience the same. 
```for commit in RepositoryMining(project_path, only_modifications_with_file_types=['.py']).traverse_commits():```

and 

```for commit in RepositoryMining(project_path, only_modifications_with_file_types=['.py'],order='revers').traverse_commits():```

Both codes start the iteration with the same commit. It starts with the oldest commit. No difference. How can we travers from newest to oldest?

Is this an expected behavior?

**Comment by ishepard** [comment]
Hi @maldil!
I can not reproduce the same problem you are having. I think you wrote `revers` instead of `reversE`. You are missing the final `e`.

This code:
```
for commit in RepositoryMining(".", only_modifications_with_file_types=['.py'], order="reverse").traverse_commits():
    print(commit.hash)
```
and this code
```
for commit in RepositoryMining(".", only_modifications_with_file_types=['.py']).traverse_commits():
    print(commit.hash)
```
produce two different results on my test.
Can you check again?

**Comment by ishepard** [comment]
For future cases, I think pydriller should return an error saying `revers` doesn't exist.

**Comment by maldil** [comment]
Oops! it works now. nice catch and thanks. Yes, an error for any invalid argument would be a nice idea.
