### ISSUE TITLE
api method to get pydriller version

### ISSUE THREAD

**Issue by fscheidt** [ishepard/pydriller#126]
couldn't found a way to get pydriller currently version when using it as an api (except reading setup.py). This is a super useful and simples (i guess) feature, mainly when dealing with multiples studies to replicate and compare their experiments results. Many python api provide a dunder method like `__version__` which I think will help a lot for the documentation process in enviroments like jupyter notebook or in the in the code it-self. Thanks for reading and considering this.

**Comment by ishepard** [comment]
Hi @fscheidt!
That indeed make sense to me. 

I will have a look at it soon, thanks!

**Comment by ishepard** [comment]
I just published a new version of pydriller with the change!
Version 1.15.2.

Now you can run `pydriller.__version__`
