### ISSUE TITLE
Cloned repositories are not deleted when in /tmp

### ISSUE THREAD

**Issue by emaiannone** [ishepard/pydriller#127]
Hello, I was working on a dataset of thousands of commits, involving about hundreds of different repositories. So I decided to use PyDriller.

**Describe the bug**
Before knowing this problem, I was creating an instance of `RepositoryMining`, giving it the list of all remote repositories URLs. I knew that the default clone location would be /tmp... and it was, but this quicky got filled up, slowing down everything.

So I decided to instantiate `RepositoryMining` in a loop, one repository per time.  
I hoped that after all objects needed by PyDriller were built, the cloned repository would be deleted, but it was not.
I also hoped that when another `RepositoryMining` object was instantiated, the previous repo would be deleted, but it was not.

I read on the documentation that they should deleted after each analysis:
>If you pass an URL, PyDriller will automatically create a temporary folder, clone the repository, run the study, and finally delete the temporary folder.

**To Reproduce**
Have /tmp and just give to RepositoryMining a huge number of remote repository such that your /tmp directory is filled up.

**How I fixed**
After having decided to instantiate `RepositoryMining` in a loop (one repository per time), I used `os` and `shutil` libraries to manually delete the cloned repository. In fact, knowing that the directory of the cloned repo has the same repo name, I checked for `/tmp/PROJECT_NAME`.  
I could get PROJECT_NAME from the remote repository URL. 

**OS Version:**
Manjaro Linux, 19.0.2

**Comment by ishepard** [comment]
Hi @emaiannone!
Thank you for catching this.

Well, needless to say that this should not happen 😄 I will have a look at it ASAP! thanks

**Comment by ishepard** [comment]
There was indeed an error due to some recent changes I made.
Now it should be fixed in version 1.15.2.

Thank you again!
