### ISSUE TITLE
traverse_commits() fails when working with specific git repository.

### ISSUE THREAD

**Issue by jemaf** [ishepard/pydriller#129]
**Describe the bug**
I am using pydriller to fetch git information from a list of GitHub repositories. For some reason, `traverse_commits()` is failing for the repository `https://github.com/jbrowncfa/Cryptobomb`. Here is the error:

```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list --reverse HEAD --
  stderr: 'fatal: not a git repository (or any of the parent directories): .git
```
I tried using both remote (GitHub URL) and local (cloning it first) methods. Same problem happened.
Curiously, I can execute `git rev-list --reverse HEAD --` with no issue in the terminal.

**To Reproduce**
```
from pydriller import RepositoryMining

repo = RepositoryMining("https://github.com/jbrowncfa/Cryptobomb")
commits = [c for c in repo.traverse_commits()] # error
```
**OS Version:**
Using docker. Here is my Dockerfile:
```
FROM python:3.6

ENV GIT_DISCOVERY_ACROSS_FILESYSTEM=1
RUN apt-get update
RUN apt-get install -y git 
```

Thanks!

**Comment by ishepard** [comment]
Hi @jemaf!
Thank you for opening the issue.

The problem seems to be with GitPython itself, for some reason. 

```
from git import Repo

repo = Repo('/tmp/Cryptobomb')
for commit in repo.iter_commits():
    print(commit.hexsha)
```
I will have a look into it, and maybe open an issue on Gitpython. But this is not related to Pydriller itself so I will close the issue 😄 

BTW: do you have other repositories where it's failing? Because I tried some of mine and it works in all of them..I am trying to understand why in this one it doesn't

**Comment by jemaf** [comment]
Hi @ishepard,

Thanks for the quick return!
I didn't realize the problem was with a third-party library, feel free to close this issue 😉.

This was the first repo in which I got an error from the list I'm mining, so I'm not sure if it can happen again. 
If that helps, I can let you know in case I find other sorts of issues.

**Comment by jemaf** [comment]
BTW I've just opened this issue at GitPython ([here](https://github.com/gitpython-developers/GitPython/issues/1016)).

**Comment by ishepard** [comment]
Perfect! Thank you!
