### ISSUE TITLE
GitRepository get_list_commits is missing commits

### ISSUE THREAD

**Issue by fengxia41103** [ishepard/pydriller#130]
**Describe the bug**
`get_list_commits` will miss a hash, while `get_commit(<hash>)` function will return a valid object.

**To Reproduce**
I manually clone the same repo to local using two different methods:
A: `git clone <repo url>`
B: `git clone --mirror <repo url>` (see https://git-scm.com/docs/git-clone)

There was a particular hash I was troubleshooting. 

If using `get_list_commits` on A, it will find the hash.

If using `get_list_commits` on B, it will not find the hash. However, if I do `get_commit(<hash>)` function on B, it will return  a valid Commit object.

**OS Version:**
Ubuntu 20.04 LTS
Python: 3.6.9

pydriller was installed via `pip install`

**Comment by ishepard** [comment]
Hi @fengxia41103!
`get_list_commits` runs `git rev-list` under the hood. If the commit is not reachable from `HEAD`, it will not be analysed. This is the same if you run `git log` or `git rev-list` from the terminal.

`get_commit(<hash>)` on the other hand returns a specific commit (*i.e.*, `git show <hash>`), no matter in what branch it is. So it will return the correct commit.

Try to run `RepositoryMining` with `include_refs=True`, that is the same of using `git log --all`. It will probably return the commit you want to analyse as well.

As a rule of thumb, try to run the same command on your terminal, if the commits are different then we got a problem 😄

**Comment by ishepard** [comment]
I will close this issue assuming you have solved the issue 😃
