### ISSUE TITLE
default of reverse traverse

### ISSUE THREAD

**Issue by mnagel** [ishepard/pydriller#131]
**Describe the bug**
RepositoryMining doc says:
        :param str order: order of commits. It can be one of: 'date-order',
            'author-date-order', 'topo-order', or 'reverse'. Default is reverse.
But I seem to observe different behavior between setting reverse and skipping the option.
The code in conf.py also looks as if reverse was NOT the same as the default:

```
        if not order:
            kwargs['reverse'] = True
        elif order == 'reverse':
            kwargs['reverse'] = False
```

**Comment by ishepard** [comment]
Hi @mnagel,
thank you for catching this! I forgot to update the docs.
This is the new docs, as reported [here](https://pydriller.readthedocs.io/en/latest/repositorymining.html).

- **order** (str): one between ‘date-order’, ‘author-date-order’, ‘topo-order’, and ‘reverse’ (see [this](https://git-scm.com/docs/git-rev-list#_commit_ordering) for more information). NOTE: By default, PyDriller returns the commits from the oldest to the newest. If you need viceversa instead (from the newest to the oldest), use “order=’reverse’”.

Is it better?
