### ISSUE TITLE
Support `~` as a path prefix (for `GitRepository#files`) or at least clarify in the docs

### ISSUE THREAD

**Issue by loeschg** [ishepard/pydriller#133]
**Is your feature request related to a problem? Please describe.**
I was exploring this library, particularly the `GitRepository#files`. I supplied a repo path that included the home shorthand `~/repos/test-repo` which resulted in an empty array. Switching to the fully qualified path got me the expected results. 

**Describe the solution you'd like**
I'd like to see the home directory shorthand supported or at least have it documented that you need a relative or full path when constructing the object.

**Comment by ishepard** [comment]
Hi @loeschg! Sorry for the late reply!
I think clarifying this in the docs will indeed help.
Python `os.walk` indeed can not accept a relative path, but it can be solved using `asbpath`. 
TBH, I would like to keep the behaviour similar to "the python way", so no relative paths.
I will update the docs! Thanks!
