### ISSUE TITLE
Mistakenly identify the "for" loop in Java "Commons-lang" as a method. 

### ISSUE THREAD

**Issue by aooXu** [ishepard/pydriller#135]
# Describe the bug
Hi, I find that the PyDriller mistakenly handles the for loop in the repository "Common-Langs" on GitHub as a method. 
Because, I downloaded the repository and ran the mining program locally, I think the copy of my codes is not enough to reproduce the bugs. 
I only list all parameter and information below and if you need the code I use for mining please tell me. 

# To Reproduce
* Repository: "Commons-lang"
* URL: "https://github.com/apache/commons-lang/"
* Commits: "96c30e248d6d27a1df8e26be14aa10c633168cdb"
* FilePath: "src/main/java/org/apache/commons/lang3/time/FastDateParser.java"
* Class: FastDateParser::CaseInsensitiveTextStrategy, 
* Method: CaseInsensitiveTextStrategy() //Constructor
* Line: 612 // for(Map.Entry<String, Integer> entry : keyValues.entrySet()) 

![image](https://user-images.githubusercontent.com/35974430/89739151-2762bd80-da76-11ea-812f-2ed26b205f7f.png)

# OS Version:
MAC OS 10.15.6 (19G73), 
Python 3.7 with PyDriller 1.15.2
in PyCharm 2020.1.2

**Comment by aooXu** [comment]
it also identify certain "if" statements in the Common-Langs as method. 
One example is the if statement in commit "[155943d345e646cbabb301bf5ee2c890db7da795](https://github.com/apache/commons-lang/commit/155943d345e646cbabb301bf5ee2c890db7da795)", 

![image](https://user-images.githubusercontent.com/35974430/89741305-fe4b2880-da87-11ea-8c58-50b142461f5f.png)

**Comment by ishepard** [comment]
Hi @aooXu!
Thank you for opening the issue.
We use Lizard (https://github.com/terryyin/lizard) to calculate code metrics. 
Could you please open the issue there and link it to this one? They will be able to solve it.

Thank you!

**Comment by aooXu** [comment]
> Hi @aooXu!
> Thank you for opening the issue.
> We use Lizard (https://github.com/terryyin/lizard) to calculate code metrics.
> Could you please open the issue there and link it to this one? They will be able to solve it.
> 
> Thank you!

Oh, I see. Thank you a lot for the reply and I will report this issues to the them.
