### ISSUE TITLE
Can't retrieve source code when commit change is only with respect to Path

### ISSUE THREAD

**Issue by farrerm** [ishepard/pydriller#136]
Hello, I'm using PyDriller to mine data about Java projects.  I seem to have found some behavior that I haven't seen discussed anywhere.

If there is a commit for which the only change is moving a source code file to a new directory, PyDriller returns this as a "change in commit.modifications".  However, when I ask PyDriller for the change.source_code for that file, it returns None.  Similarly, change.source_code_before for such a commit also returns None.

Wondering if there is a workaround for this?  Not a huge deal, but I am losing some data when I cannot retrieve the source code for these commits.  

I should mention, I would rather avoid doing something like recording the source code for all changes in the repo, their current path, and them linking them to the new change if this happens by way of change.old_path.  Although this approach makes intuitive sense, I would be storing a huge amount of source code somewhere (saving to disk?) to make such a solution work. 

Thanks!

**Comment by ishepard** [comment]
Hi @farrerm!
Sorry for the late reply, I was in vacation in the past weeks 😄 
Anyway, I haven't seen this behaviour personally, I need to better investigate. Can you provide me with a commit with this kind of behaviour? Thanks!

**Comment by farrerm** [comment]
Hi, I ended up deciding that this behavior is not super important.  I ended up searching without requiring a match for path.  We loose a small amount of data which seems acceptable.  Anyway, I first observed this by traversing over about 50 repos.  But, the easiest way to observe it is to make a simple test repo.

What I did to confirm this was make a simple repo containing a java file.  That is commit 1.  When I ask PuDriller for the source code, it returns it.  Then, I move that single java file to a new directory I made inside the repo.  And I make that commit 2.  If you try this, you should observe that when asking pydriller for the change.source_code for commit 2, it returns None.

Btw, I’m working with Anand Sawant.  He said he knows you. 

Matt

**Comment by ishepard** [comment]
Oooh of course I know Anand! Good luck working with him 😨 no I'm joking, he's a great guy 😃 

I wrote a small test and indeed it seems that for renamed files Git doesn't store source codes..which kind of makes sense, since the source code isn't changed.
I am expecting though that if the file is renamed and changed, then Git stores the source code. 
So yes, this is the normal behaviour of Git and Pydriller isn't doing anything wrong 😄 but thanks for catching this, I will update the docs!
