### ISSUE TITLE
include_remotes option and commit.branches

### ISSUE THREAD

**Issue by sposs** [ishepard/pydriller#145]
**Describe the bug**
The include_remotes does not add the '-r' option to the git branch --contains commit as it should.

**To Reproduce**
```python
for commit in RepositoryMining(repo.working_tree_dir, since=since, include_refs=True, include_remotes=True).traverse_commits():
        for b in commit.branches:
              print(b)
```
If the commit is not local, the branches is empty.
To fix it, I have added the "-r" option to the `_get_branches` method, and it seems to behave properly. I do not know if that's the right solution though. If it is, I can attempt to provide a pull request.

**OS Version:**
 Linux (although I don't think it matters)

**Comment by ishepard** [comment]
Hi @sposs!
Thanks for catching this. Indeed you are right, in this case it doesn't work.
We should add "-a" if "include_refs" is set to True, and "-r" if "include_remotes" is set to True.

You can see whether these flags are set to True using `self._conf.get('include_remotes')`.
Feel free to drop the PR whenever you want 😄
