### ISSUE TITLE
How to obtain source code of a renamed file?

### ISSUE THREAD

**Issue by shehan** [ishepard/pydriller#148]
I read in the [documentation](https://pydriller.readthedocs.io/en/latest/modifications.html?highlight=source_code#modifications) that the `source_code` attribute of the `Modifications` property is none if the file is renamed. Is there a workaround to obtain the source code for a renamed file?

Thanks!

**Comment by ishepard** [comment]
Hi @shehan!
Maybe in the documentation is not well explained, my bad. 
If the author of the commit doesn't change the content of the file (for example, he changes the file extension, or file permissions, or he renames the file), git doesn't carry source code or diff information, as they are not changed. 
This is a limitation of git.

However, if the file content **is** changed, diff and source code will be there. So even if the file is renamed, the source code will be there **only if** the content is changed.
I hope it's clearer now :) 

Cheers
