### ISSUE TITLE
Add shortstats data to the commit object

### ISSUE THREAD

**Issue by butterl** [ishepard/pydriller#150]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Could the call of below code get change data like `git log --shortstat`

```
for commit in RepositoryMining(repo_path).traverse_commits():
    print(str(commit.add) + "," + str(commit.add))

```
**Additional context**

**Comment by ishepard** [comment]
Hi @butterl!
If I got the question right, you would like to see the output of "--shortstat" while traversing the commits.
Shortstats returns the total number of modified files, as well as number of added and deleted lines. 
You can calculate these metrics manually if you want, but indeed this could be a nice addition to the commits object. 
We could add `commit.modified_files`, `commit.added_lines`, commit.deleted_lines`. 

Would you like to try implementing this? 😄

**Comment by butterl** [comment]
#151  add reference with issue and pr changes

**Comment by butterl** [comment]
PR is merged， thanks for the helping！
