### ISSUE TITLE
`get_commits_last_modified_lines` gives incorrect results

### ISSUE THREAD

**Issue by david-siqi-liu** [ishepard/pydriller#155]
I am comparing the results between the latest release and version 1.8, and I believe the results from the latest release are incorrect.

Consider the following commit on Openstack/Glance: https://github.com/openstack/glance/commit/4f124bdcd329b0cd99053731467ed4952b9915ce

Under the newest version:
```
{'glance/db/registry/api.py': {'265659e8c34865331568b069fdb27ea272df4eaa', 'de8eba091b97db906da76ce48b537fde7cbc3810'}, 

'glance/db/simple/api.py': {'d635c418ed22f5888adac67a4245dfcd1e3629ec', '1e50b993c0cebd3c1d22ca7636cb608686a1f526', 'ac1c9ace1e57fb2ca76b78f2ba964ff3686449dd', 'cc900ef68fab491905823539901dcdaf3057be4f', '265659e8c34865331568b069fdb27ea272df4eaa', '0f2d8d4d7c83829a1e78150cbe946068080f9631'}, 

'glance/db/sqlalchemy/api.py': {'d635c418ed22f5888adac67a4245dfcd1e3629ec', '1e50b993c0cebd3c1d22ca7636cb608686a1f526', 'ac1c9ace1e57fb2ca76b78f2ba964ff3686449dd', 'cc900ef68fab491905823539901dcdaf3057be4f', '265659e8c34865331568b069fdb27ea272df4eaa'}}
```

Under v1.8:
```
{'265659e8c34865331568b069fdb27ea272df4eaa', 'de8eba091b97db906da76ce48b537fde7cbc3810'}

{'ac1c9ace1e57fb2ca76b78f2ba964ff3686449dd', '1e50b993c0cebd3c1d22ca7636cb608686a1f526', '265659e8c34865331568b069fdb27ea272df4eaa'}

{'1e50b993c0cebd3c1d22ca7636cb608686a1f526', '265659e8c34865331568b069fdb27ea272df4eaa'}
```

We can see that the newest version gives way more commits. However, if you look at the blame for the `simple/api.py` file:
https://review.opendev.org/c/openstack/glance/+/387660/3/glance/db/simple/api.py

You can see that only 3 commits - `{'ac1c9ace1e57fb2ca76b78f2ba964ff3686449dd', '1e50b993c0cebd3c1d22ca7636cb608686a1f526', '265659e8c34865331568b069fdb27ea272df4eaa'}` actually touched those lines. The other commits given by the newest version, even thought touched the files, did not touch the lines.

**Comment by ishepard** [comment]
Hi @david-siqi-liu!
Thanks for catching this. Would you be able to investigate where the problem is and open a PR?

Thank you!

**Comment by david-siqi-liu** [comment]
Sure I will take a look. Great work by the way, love the package!

**Comment by david-siqi-liu** [comment]
After much testing, I believe that this change of "ignoring whitespaces when blaming" is causing the differences:
https://github.com/ishepard/pydriller/commit/48f482d1d881782b61ea2653d053decfe1049dbe

For the particular commit I mentioned in my post, I can confirm that the "ignoring whitespace changes" change is working as intended. As such, I will close this issue.
