### ISSUE TITLE
Efficient accessing of commit modifications for specific file 

### ISSUE THREAD

**Issue by S3j5b0** [ishepard/pydriller#168]
Hi, I was a bit unsure if I should label this issue as a feature request, but here it is anyway.
I'm doing a project where I need to traverse through all python files in a project and calculate churn for each file. I found this formula for calculating the churn.
[Lines Added] + [Lines Deleted] + [Lines Modified].
And now I made this snippet for getting these churn metrics for a specific file in a  local git repo, and then calculating the churn:
from pydriller import RepositoryMining

filepath ="/home/ask/Git/tweeda/Main.py"
filename = filepath.split('/')[-1]

linesChanged = 0 
linesdeleted = 0
linesAdded = 0

for commit in RepositoryMining("/home/ask/Git/tweeda", filepath=filepath).traverse_commits():
for m in commit.modifications:
 if (filename == m.filename):
            linesdeleted = linesdeleted + m.removed
            linesAdded = linesAdded = m.added
            linesChanged = linesChanged = m.changed_methods # this is not correct, but how do I acces modified lines?
churn = linesChanged + linesAdded + linesdeleted

print(churn)

So theres two issues here:
1.
Firstly, I should be able to get a measure for how many lines have been modified. How do I do this?
2.
Secondly, this is not efficient. In order to access all the metrics for one file speficially, and the commits that have affected it, I iterate through all commits affecting that file, and in an indented loop through all the modifications that involved in that commit, and only picking the ones that affect the specific file I want to target.
A lot of unnecessary iteration going on here.

How can I try to solve these two issues?

**Comment by ishepard** [comment]
Hi @S3j5b0! 
> 1.
> Firstly, I should be able to get a measure for how many lines have been modified. How do I do this?

In Git there is no modified line, there is only added or deleted. So there is now way to get this, unless you create your own euristic. Also, Churn is usually calculated as Added + Deleted lines.

>2.
> Secondly, this is not efficient. In order to access all the metrics for one file speficially, and the commits that have affected it, I iterate through all commits affecting that file, and in an indented loop through all the modifications that involved in that commit, and only picking the ones that affect the specific file I want to target.

What I would if I were you is to build up a dictionary of files, keeping it updated when a file is added:

```
churn_per_file = {}
for commit in RepositoryMining("repo").traverse_commits():
    for modified_file in commit.modifications:
        churn = modified_file.removed + modified_file.added
        if modified_file.new_path not in churn_per_file: # Here you should keep track of renaming, add a new "if-else"
            churn_per_file[modified_file.new_path] = 0
        churn_per_file[modified_file.new_path] = churn_per_file[modified_file.new_path] + churn
```
At the end you are gonna have a dictionary with files as keys, and values the churns.

**NOTE**: you need to keep track of renamings. 

I didn't test the code, take it as an example 😄

**Comment by ishepard** [comment]
Yeah I don't know how the other program works, but since you have a dictionary with all the files it should work right? 😄  I mean, you could run this once at the beginning of your program, and then
```
# my example code here

# your code here:
for file in all_files:
    churn = churn_per_file[file]
```

**Comment by S3j5b0** [comment]
yes, it works super well, it was just that I was hoping that I could include the collection of churn metrics in my already existing loop.

But this also works super! thx a lot
