### ISSUE TITLE
Choose calculation variant to calculate the code churn metric

### ISSUE THREAD

**Issue by glato** [ishepard/pydriller#175]
Hi @ishepard,

I've just discovered your tool, thanks for the great work.

I sometimes see/read in literature (and in some implemented solutions) the following code churn metric/variant when it is related to lines of code:

```
added_lines + deleted_lines (+ modified_lines)
```

As far as I can see (reproduce), currently pydriller seems to calculate code churn in `code_churn.py` / `CodeChurn` class in the `_initialize` method in the following way:

```python
churn = modified_file.added_lines - modified_file.deleted_lines
```

My proposal or idea would be to make the calculation somewhat configurable, e.g. to use the initializer of the `CodeChurn` class

```python
def __init__(self, path_to_repo: str,
                 since=None,
                 to=None,
                 from_commit: str = None,
                 to_commit: str = None,
                 ignore_added_files=False,
                 add_deletions_to_churn=False
                 ):
```

so that we could choose, which code churn variant should be used for the calculation. This could be set to False by default, so there would be no breaking changes for implementations that use it in the current way.

This could also be further extended to have a more flexible way of choosing a calculation from multiple variants maybe?

I would need this kind of calculation and it would be very helpful if I could use pydriller and simply configure the `CodeChurn` class for this. If you think this could be a nice addition but don't have much time, I'd be happy to contribute, just let me know.

Again - thanks a lot for pydriller!

**Comment by ishepard** [comment]
Hi @glato!
TBH, I also do remember code churn to be the sum of added and deleted lines. Let me double check with the author of that code @stefanodallapalma.
Also, in CC @mauricioaniche @marco-c, they have done more studies using similar metrics.

**Comment by ishepard** [comment]
@glato
BTW, I like the idea of having that flag added. Feel free to make the change!
Now the question is what should be the default behaviour 😄

**Comment by stefanodallapalma** [comment]
Hi all,

I based the implementation on the definition that can be found in this [paper](https://dl.acm.org/doi/pdf/10.1145/1368088.1368114?casa_token=xMbRQpXPKSMAAAAA:Rh7O20PFiC-eYG74acUuS8jhzLnxaEt5hsL_52iFrs3QO8IHdVSLO4RrfBq4PMfGRhRd2w6nW2ionA) (Table 4), that is, _"sum of (added lines of code – deleted 
lines of code) over all revisions"_. To be honest, I do not have much experience with that metric, therefore advises are welcome.
Personally, I like the idea of adding that flag. Nevertheless, atm I'd propose to add it as an alternative behavior to avoid breaking changes for implementations that use it in the current way, and eventually set as default when we receive further feedback.

**Comment by glato** [comment]
Hi all,

I've created the PR #176 with the proposed implementation of the variant.
