### ISSUE TITLE
ModuleNotFoundError: No module named 'pydriller.metrics'

### ISSUE THREAD

**Issue by armandossrecife** [ishepard/pydriller#177]
**Description**
I'm trying to use the module metrics from pydriller but when I try to import the module via  
from pydriller.metrics.process.code_churn import CodeChurn 
I found the following error message: ModuleNotFoundError: No module named 'pydriller.metrics'

**To Reproduce**
Steps to reproduce the bug. For example, a specific commit in a repository, and/or a modification.
Import module via 
from pydriller.metrics.process.code_churn import CodeChurn 

When I run the following code: 

repository = '/Users/armandosoaressousa/git/hadoop'
v1 = 'hadoop-branch-2.0.5'

repository = repository + '/' + v1

metric = CodeChurn(path_to_repo=repository,
                   from_commit='5128a9a453d64bfe1ed978cf9ffed27985eeef36',
                   to_commit='a882b627e3e70d8f62b23bfb5517f0aad832fb46')
files_count = metric.count()
files_max = metric.max()
files_avg = metric.avg()
print('Total code churn for each file: {}'.format(files_count))
print('Maximum code churn for each file: {}'.format(files_max))
print('Average code churn for each file: {}'.format(files_avg))

The system show the following message: 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-be59d6735ce1> in <module>
----> 1 from pydriller.metrics.process.code_churn import CodeChurn

ModuleNotFoundError: No module named 'pydriller.metrics'
**OS Version:**
MacOS Mojave - version 10.14.6 - Darwin Kernel Version 18.7.0

**Comment by armandossrecife** [comment]
I think that this problem is related to changing version of Pydriller. I my case I was using version 1.15, and I observed some modifications in new version 2.0. 
I removed old version of Pydriller via pip uninstall pydriller, after that I install new version of Pydriller via pip install pydriller, finally this problem is resolved.

**Comment by armandossrecife** [comment]
I suggest that the Pydriller documentation available on [https://pydriller.readthedocs.io/en/latest/commit.html](https://pydriller.readthedocs.io/en/latest/commit.html) should be updated to reflect the modifications of new version of Pydriller.

**Comment by ishepard** [comment]
Hi @armandossrecife! Happy that the issue was resolved! Cheers
