### ISSUE TITLE
New feature to clarify ModifiedFile line change type

### ISSUE THREAD

**Issue by albuswhite** [ishepard/pydriller#178]
Can pydriller support clarify ModifiedFile line change type ? Although we know how many lines have been changed, we may want to know the type of the lines. Maybe blank line, source code or comment line

**Comment by ishepard** [comment]
Hi @albuswhite! Thanks for the question!

This feature wouldn't be really related to Git (it would be actually language dependant) so it will be hard to maintain. 
I think the best way for you to check this would be to manually do it in your code.
