### ISSUE TITLE
No analysis without temporary clone?

### ISSUE THREAD

**Issue by StephanSchmidt** [ishepard/pydriller#183]
Is there a way to read the commit history of a remote repository without creating a temporary clone?

Or can this done without source files and a shallow copy?

**Comment by ishepard** [comment]
Hi @StephanSchmidt! Thanks for the question. 
I am not sure what you mean.
You have 2 ways to analyse a Git repo, by manually cloning it before where you want and passing the path to Repository, or let pydriller cloning it in a temporary directory.

**Comment by StephanSchmidt** [comment]
I would like to read the commit log of a remote history without transffering the source files.

**Comment by ishepard** [comment]
Ah I see, no then it's not possible, the repository needs to be on local disk.

**Comment by ishepard** [comment]
If you don't need files, have a look at GHTorrent, it's a GitHub mirror with commits information.

**Comment by StephanSchmidt** [comment]
Thanks!
