### ISSUE TITLE
Should we handle commits order when num_workers > 1?

### ISSUE THREAD

**Issue by stefanodallapalma** [ishepard/pydriller#184]
This may not be a bug, considering the nature of multithreading.
However, when traversing commits using a number of workers greater than 1 the commits are in random order (depending on the jobs execution time). 
I am wondering whether we should handle this situation when `order != None` [here](https://github.com/ishepard/pydriller/blob/010c1ea5eab4dea9c34b719efc9fb8537c76e94a/pydriller/repository.py#L235). For example, by waiting for the jobs to finish and then order the commits. What do you think? 
Below an example of output using `order=reverse` and  `num_workers=8`.

```python
for commit in Repository('https://github.com/ishepard/pydriller', from_commit='010c1ea5eab4dea9c34b719efc9fb8537c76e94a', to_commit='94532fcac0eddd20c364585a4cf76e97d45df4bd', order='reverse', num_workers=8).traverse_commits():
    print(commit.hash)
```

**Expected**
```
010c1ea5eab4dea9c34b719efc9fb8537c76e94a
da846f2e75d138d64f8405f5896e4338f1e14319
2ad53b0544e765187d4a23fdb4096d26bd663afb
01c8e0abef39a7bd378ccc795ab9dafe11d7470f
94532fcac0eddd20c364585a4cf76e97d45df4bd
```

**Obtained**
```
2ad53b0544e765187d4a23fdb4096d26bd663afb
da846f2e75d138d64f8405f5896e4338f1e14319
010c1ea5eab4dea9c34b719efc9fb8537c76e94a
01c8e0abef39a7bd378ccc795ab9dafe11d7470f
94532fcac0eddd20c364585a4cf76e97d45df4bd
```

Please note, the test above is flaky: sometimes it fails and others it passes.

**Comment by ishepard** [comment]
I don't think we should do anything in this case, this is expected behaviour. I think in the documentation is written that if we use num_workers > 1 the order is not maintained.

**Comment by stefanodallapalma** [comment]
Yeah, as I imagined. I couldn't find that. I've added a note in the docs in https://github.com/ishepard/pydriller/pull/185.
