### ISSUE TITLE
Is modified_files working well?

### ISSUE THREAD

**Issue by NitescuLucian** [ishepard/pydriller#195]
**Describe the bug**
I do not understand why in some cases modified_files does not show any file for commits that contains "modified files". Should it not be there or I am getting this wrong?

**To Reproduce**
For any repository, do this:
```
commits=pydriller.Repository(path_to_repo=[path], since=datetime.strptime(date, '%Y-%m-%d'),only_in_branch=branch).traverse_commits()
for commit in commits:
    if commit.modified_files == []:
        print('Yes, but why?')
        continue
    else:
        print('Ok.')
```

Output:
```
Ok.
Ok.
Ok.
Yes, but why?
Ok.
Yes, but why?
Ok.
Ok.
Ok.
Ok.
Ok.
```

**OS Version:**
Linux

**Comment by NitescuLucian** [comment]
Also, it does get the right number of commits? From where it gets the other 2? I do use `only_in_branch=branch`.

**Comment by stefanodallapalma** [comment]
Hi @NitescuLucian,

please provide the value of the variables `path`, `date` and `branch` to enable reproducibility.

Also, traverse_commits() returns a Generator. You might want to do the following to store the commits objects:

```
commits = list(pydriller.Repository(path_to_repo=[path], since=datetime.strptime(date, '%Y-%m-%d'),only_in_branch=branch).traverse_commits())
```
