### ISSUE TITLE
only_in_branch Repsitory option only works if branch is already checked out

### ISSUE THREAD

**Issue by Lukasdoe** [ishepard/pydriller#196]
**Describe the bug**
When creating a new Repository with the `only_in_branch` option set to something different than the default branch, the commits can't be traversed (`Repository.traverse_commits()` throws an exception). This is the case, because the underlying git wrapper only calls the `git rev-list <desired_branch_here> --`. This however does not work if the default branch (e.g. not "master" or "main") is different than the searched branch and the commit(s) from the searched branch aren't also in the currently checked out branch.

**To Reproduce**
1. Search a public git repository with a default branch other than the master / main branch and the master / main branch pointing to a commit that is not also on the default branch (e.g. a merge commit).
2. Create a Repository: `repo = Repository(clone_url, order="reverse", only_in_branch="master")`
3. Call `list(repo.traverse_commits())` or step through the generator in any other way.

**OS Version:**
Linux 5.13.0-21-generic #21-Ubuntu SMP (uname -srv)

**Comment by Lukasdoe** [comment]
I'd be happy to implement a fix by myself and create a PR, but I'm currently unsure whether this is more of a problem in `pydriller` or in `GitPython` which doesn't check out the supplied `rev` in the `Repo.iter_commits` command.

**Comment by ishepard** [comment]
Hi @Lukasdoe ! I am not sure I understood correctly.
> with the only_in_branch option set to something different than the default branch, the commits can't be traversed
This should work, that's exactly the definition of the "only_in_branch" filter. For example, see [this test](https://github.com/ishepard/pydriller/blob/master/tests/integration/test_commit_filters.py#L93). I traverse a branch that is not the default one (not main, it's called 'b1')

> git repository with a default branch other than the master / main branch and the master / main branch pointing to a commit that is not also on the default branch (e.g. a merge commit).
Pydriller doesn't have the definition of master/main branch. The master/main branch will be the one that is checked out when you first run Pydriller. So if you checkout b1 first, that's gonna be the master/main branch.

**Comment by stefanodallapalma** [comment]
Hi @Lukasdoe,

it seems you have a similar problem already addressed [here](https://github.com/ishepard/pydriller/issues/181#issuecomment-852090913).
Let me know if that solves the issue.

**Comment by Lukasdoe** [comment]
This looks like the same issue, yes. I didn't try the solution yet, but it sounds like this is already solved, thanks!

You might still have to add a short info to the docs :)
