### ISSUE TITLE
Detect http:// as remote repository

### ISSUE THREAD

**Issue by thtrummer** [ishepard/pydriller#197]
Currently only "git@" and "https://" are treated as remote.

**Comment by ishepard** [comment]
Didn't know there were still repos with `http://`. Are we sure? 😄 

Anyway, it's a very simple change in [repository.py](https://github.com/ishepard/pydriller/blob/master/pydriller/repository.py#L147).

Feel free to do a PR and, if you can, also add a test.

**Comment by thtrummer** [comment]
Internal networks in companies sometimes still use `http://`. I didn't see a good way to add a test, but feel free to propose one.

**Comment by ishepard** [comment]
Close in #200
