### ISSUE TITLE
commit_url attribute for Commit

### ISSUE THREAD

**Issue by josemorenoo** [ishepard/pydriller#202]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, there isn't a way to get the path of a specific `Commit`, e.g. `github.com/domain/repo_name/commit/hash`. `project_path` appears to be the absolute local path the the temp dir where the repo is cloned.

**Describe the solution you'd like**
a simple attribute like `commit_url` for the `Commit` object would be very useful.

**Comment by stefanodallapalma** [comment]
Hi @josemorenoo,

I don't think that attribute should be added; for two reasons:

1. PyDriller targets Git repositories. The URL you mentioned is GitHub's, but could link to any other platform that displays the commit's info, e.g., GitLab, or server. Therefore, it is out of PyDriller's scope.
2. You can generate the URL when traversing the commits by accessing the attribute `commit.hash` and the `path_to_repo` passed to the `Repository` object, in case it is a remote URL.  

Hope that helps!

**Comment by ishepard** [comment]
Hi @josemorenoo,
yes I also think this is not a feature for Pydriller. You are probably confusing a Git repository with a GitHub repository.
Pydriller is only able to analyze git repositories, it doesn't have access to GitHub.

Anyway, see Stefano's comment if you want to trace back the URL (not sure why you would have to do it though).

Cheers

**Comment by josemorenoo** [comment]
@stefanodallapalma @ishepard you're both right, thanks!
