### ISSUE TITLE
Getting the list of files in a repository using pydriller's Git wrapper does not include ".github/workflows"

### ISSUE THREAD

**Issue by tromai** [ishepard/pydriller#203]
**Is your feature request related to a problem? Please describe.**
When trying to use pydriller's Git wrapper to get the list of files in the repository, the result does not include `.github/workflows` because this [method](https://github.com/ishepard/pydriller/blob/036978c2e1f2d849395a23f2dba62d67b0c17ba7/pydriller/git.py#L155) exclude any paths with `.git` in it.

**Describe the solution you'd like**
Can it include `.github/workflows` as the result? 

Thank you.

**Comment by stefanodallapalma** [comment]
Hi @skyworld42,

feel free to edit the condition at [line 163](https://github.com/ishepard/pydriller/blob/036978c2e1f2d849395a23f2dba62d67b0c17ba7/pydriller/git.py#L163) accordingly and open a pull request. Please, do not forget to provide test(s) for the changes :smile:

**Comment by ishepard** [comment]
Closing since no interest
