### ISSUE TITLE
Implement Git Blame

### ISSUE THREAD

**Issue by NIKHITH-SANNIDHI** [ishepard/pydriller#204]
I tried looking up an API for git blame in PyDriller but looks like the closest I find is [this](https://pydriller.readthedocs.io/en/latest/reference.html?highlight=blame#pydriller.git.Git.get_commits_last_modified_lines).

I was wondering if there is any functionality that implements git blame for a given file?
Or is there any way I can get the commit hash (or [Commit object](https://pydriller.readthedocs.io/en/latest/commit.html)) if I provide the repository path, the file path, and the line number?

Thank you in advance for your help.

**Comment by ishepard** [comment]
Hi @NIKHITH-SANNIDHI !

No there is currently no way to get the blame of the file. It shouldn't be too hard to add to the ModifiedFile object, if you'd like to create a PR 😄 

Thanks!

**Comment by ishepard** [comment]
Closing since no interest
