### ISSUE TITLE
ModifiedFile Complexity

### ISSUE THREAD

**Issue by arakhia** [ishepard/pydriller#208]
Hi There,

Thanks for such an amazing tool. I have a questions regarding [ModifiedFile ](https://pydriller.readthedocs.io/en/latest/modifiedfile.html) Complexity, how it actually calculated? it is an aggregation of methods complexity? or it calculates class complexity? in that case, does it take into account nested classes as well or ignore them?

Thanks for your time

**Comment by ishepard** [comment]
HI @arakhia ! I use Lizard (https://github.com/terryyin/lizard) to calculate the various metrics.
