### ISSUE TITLE
Get latest commits

### ISSUE THREAD

**Issue by 0x0elliot** [ishepard/pydriller#210]
**Is your feature request related to a problem? Please describe.**
Right now Pydriller has basic filtering options which are decent as well. Like:
https://pydriller.readthedocs.io/en/latest/repository.html?highlight=new%20commits#filtering-commits

And you can get basic generators by the methods near the following method:
https://pydriller.readthedocs.io/en/latest/reference.html?highlight=new%20commits#pydriller.git.Git.get_list_commits

But from my understanding, it returns the commits from the **start**. This might end up being a slight inconvenience. 

**Describe the solution you'd like**
If done right, A good generator that lists commits in the order newest -> oldest.

**Comment by stefanodallapalma** [comment]
HI @0x0elliot,

by default Pydriller returns the commits from the newest, i.e., most recent, to the oldest.
To traverse commits in a different order - for example, chronologically - take a look at the parameter `order` of the object `Repository` [here](https://pydriller.readthedocs.io/en/latest/reference.html#pydriller.repository.Repository).

**Comment by 0x0elliot** [comment]
Wonderful. Thanks for the response.
