### ISSUE TITLE
Does Pydriller have a WebApi?

### ISSUE THREAD

**Issue by ErnestFistozz** [ishepard/pydriller#225]
Hi,

Does Pydriller have a WebApi? if I so, can you point me in the right direction with regards to the documentation. I am looking at collecting metrics for specific commits in a branch. However, i don't necessarily wish to install pydriller. I would prefer to use a WebApi if exists.

**Comment by stefanodallapalma** [comment]
Hi @ErnestFistozz, 
PyDriller does not have WebApi. Personally, I do not know if someone implemented any in an external application.
Anyway, let us know if there is anything we can do to help!
