### ISSUE TITLE
Get The Issue Code That Is Associated a Commit

### ISSUE THREAD

**Issue by otonpneto** [ishepard/pydriller#228]
Create a new field on commit object to get the commits associated issues.

**Comment by ishepard** [comment]
I think you are referring to the issues in Github?
Issues don't exists in Git.

**Comment by otonpneto** [comment]
Exactly. To associate commits with github issues and their types (bugs, enhancement, ...)

**Comment by ishepard** [comment]
Then no, Pydriller is a GIt framework (not GitHub). I'd suggest you to look to GHTorrent for that.
