### ISSUE TITLE
In the modified file bring only the modified methods and not all

### ISSUE THREAD

**Issue by jlgomes** [ishepard/pydriller#24]
Include a method that brings all modified methods into a commit

**Comment by ishepard** [comment]
I like the idea! It should be pretty trivial to implement as well, since a `Modification` object has the diff, from which we can obtain the modified lines, which can then use to detect the methods changed (every method has starting and ending line). Could you do a PR?

**Comment by jlgomes** [comment]
I implemented the method that returns only the changed methods in commit, can you release the PR and validate the implementation?
