### ISSUE TITLE
file has changed, but changed_methods list is null.

### ISSUE THREAD

**Issue by baizeweiyu** [ishepard/pydriller#249]
**Describe the bug**
A repository named php/php-src, I use commit id b28b8b2fee6dfa6fcd13305c581bb835689ac3be to analyze this commit. This commit has modifiled code files. But changed_methods list is null.

**To Reproduce**
Repository: php/php-src
Commit id: b28b8b2fee6dfa6fcd13305c581bb835689ac3be 
code: Repository(my/repo/path, only_commits=commits_id).traverse_commits()
correct information: this commit change a method named phar_parse_pharfile and modified 2 lines in ext/phar/phar.c.
result: modifiled_files has 3 elements. The first element is information about 'ext\\phar\\phar.c'. New_path is 'ext\\phar\\phar.c'. Except changed_methods, it has all other information.

**OS Version:**
Windows

**Comment by ishepard** [comment]
Pydriller uses [Lizard](https://github.com/terryyin/lizard) to analize the method. My guess is that Lizard is not able to detect what the method is.
