### ISSUE TITLE
Problem with old_path

### ISSUE THREAD

**Issue by Robgua** [ishepard/pydriller#25]
I wanted to search the commit when a file was added but the result is that the old_path of the file is never None so the commit was not found. I tested this on the repository https://github.com/krb5/krb5 and the file define.h.

**Comment by ishepard** [comment]
```
for commit in RepositoryMining("/tmp/temp/krb5", single="e2261d482ee27f62a9b588b1c9f51132b582736f").traverse_commits():
    for mod in commit.modifications:
        if mod.filename == "defines.h":
            print(mod.filename, mod.old_path, mod.new_path)
```
this code returns:
```
defines.h None src/appl/telnet/telnet/defines.h
```

old_path = None. I do not see the problem.

**Comment by ishepard** [comment]
Chat offline with the author of the issue, problem solved.
