### ISSUE TITLE
why fan_in and fan_out return all zeros for all the methods？

### ISSUE THREAD

**Issue by cp3-three** [ishepard/pydriller#252]
why fan_in and fan_out return all zeros for all the methods？

**Comment by ishepard** [comment]
Pydriller uses Lizard to calculate metrics, and back in 2019 I opened an [issue](https://github.com/terryyin/lizard/issues/250) on Lizard for this. It still hasn't been solved unfortunately.

**Comment by cp3-three** [comment]
> Pydriller uses Lizard to calculate metrics, and back in 2019 I opened an [issue](https://github.com/terryyin/lizard/issues/250) on Lizard for this. It still hasn't been solved unfortunately.

think you!  I have other question in the discussions:  https://github.com/ishepard/pydriller/discussions/244.  Thank you very much if you can get an answer!

**Comment by ishepard** [comment]
Replied there 😄
