### ISSUE TITLE
Exception has occurred: ImportError 

### ISSUE THREAD

**Issue by dmc1778** [ishepard/pydriller#254]
**Describe the bug**

When I import pydriller in my python file as: 

```
from pydriller import GitRepository as PyDrillerGitRepo
```

And run the file, I get exception as follows:

```
Exception has occurred: ImportError
cannot import name 'GitRepository' from 'pydriller.repository' (/home/nimashiri/anaconda3/envs/codechecker/lib/python3.9/site-packages/pydriller/repository.py)
  File "un_infer_vfc.py", line 2, in <module>
    from pydriller import GitRepository as PyDrillerGitRepo
ImportError: cannot import name 'GitRepository' from 'pydriller.repository' (/home/nimashiri/anaconda3/envs/codechecker/lib/python3.9/site-packages/pydriller/repository.py)
```

**To Reproduce**

I am running my file in conda env. PyDriller is installed in conda env.

**OS Version:**
ubuntu22.04

**Comment by ishepard** [comment]
Hi!
GitRepository doesn't exists in Pydriller anymore, since last year. 
It's now called just `Git`. 

More in the docs: https://pydriller.readthedocs.io/en/latest/git.html
