### ISSUE TITLE
can I get a whole changed function directly ?  

### ISSUE THREAD

**Issue by Vela-zz** [ishepard/pydriller#262]
Is there are any methods that can let me extract whole function/methods string include function name function parameteres and function content at the same time.

current Methods class startline, endline attribute only extract function content , and Methods.parameters is a list.

**Comment by ishepard** [comment]
> current Methods class startline, endline attribute only extract function content 

You mean it doesn't include the first line of the function, the definition? Unfortunately these info are extracted using Lizard, so it's a feature on their side.
