### ISSUE TITLE
Enhancement: add commit categorization feature.

### ISSUE THREAD

**Issue by 0x404** [ishepard/pydriller#265]
I hope this message finds you well. I would like to discuss the potential implementation of a new feature that could greatly benefit researcher and developer using PyDriller and are interested about commit's maintenance category. As you know, understanding commit activities performed in a source code repository, could help practitioners reduce uncertainty and improve cost-effectiveness by planning ahead and pre-allocating resources.

Swanson categorizes commits into three categories in his [paper](http://www.mit.jyu.fi/ope/kurssit/TIES462/Materiaalit/Swanson.pdf): corrective, perfective, and adaptive, which has been the subject of recent studies investigating automatic commit classification. [1](https://arxiv.org/pdf/1711.05340.pdf) [2](https://www.sciencedirect.com/science/article/abs/pii/S0950584921000495)

I believe that commit’s maintenance category could also be treated as a valuable metric, similar to message, author, and committer, for further analysis of PyDriller’s results. I have implemented a method achieving about 82% accuracy in classifying commit’s maintenance category and would like to propose this feature for implementation. If this is of interest to you, I am happy to submit a formal pull request with the code changes required to implement this feature.

Thank you for considering this proposal. Please let me know if you need any further information.

**Comment by ishepard** [comment]
Mmmm adding neural networks to pydriller wouldn't work. I thought it was something statically calculated.

In this case, I'd suggest you to create your tool (that internally uses pydriller). There are other tools that use Pydriller for their specific case, like Mozilla bugzilla or such.
