### ISSUE TITLE
Crashed when want to get info from single commit with thousands of files modified.

### ISSUE THREAD

**Issue by Vela-zz** [ishepard/pydriller#267]
**Describe the bug**
Pydriller meets [deadlock/crash/Memory] issue when I want to get info(commits.files,e.g.) from an  extremely chaotic git-commit  with 2000+ files change at one time.

**OS Version:**
 WSL on windows, Ubuntu 20.04,

**Comment by ishepard** [comment]
Hey @Vela-zz! Can you give an example of such commit? Just so I can repro on my machine. Thanks!
