### ISSUE TITLE
GitRepository error: A branch named '_PD' already exists.'

### ISSUE THREAD

**Issue by davidetaibi** [ishepard/pydriller#27]
I tried to use pydriller to iterate all the commits of a project and then execute a custom command on each commit. (in my example, I simply print all the files in the directory for each commit). 

The library GitRepository is looking for a branch "_PD" that does not exist in my repository. 

Here is the script I wrote:

```
import os
from typing import re
from pydriller import RepositoryMining
from pydriller import GitRepository

DATASET_DIR= './GitTest'
gr = GitRepository(DATASET_DIR)

for commit in RepositoryMining(DATASET_DIR).traverse_commits():
    print("commit {}, date {}".format(commit.hash, commit.author_date))
    gr.checkout(commit.hash)
    
    # Print all files in the repository for the current commit
    filenames = os.listdir(DATASET_DIR)  # get all files' and folders' names in the current directory
    for filename in filenames:  # loop through all the files and folders
        print(filename)
```

This is the exception

```
 File "test_miner.py", line 37, in <module>
    gr.checkout(commit.hash)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pydriller/git_repository.py", line 115, in checkout
    self.git.checkout('-f', _hash, b='_PD')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git checkout -b _PD -f 3dfc48d9e65d907c0fd2cf0b34c510c9f5355984
  stderr: 'fatal: A branch named '_PD' already exists.'
```

**Comment by davidetaibi** [comment]
Thank you. Checking out manually the master, it works. 

However, when you launch the same script twice, you obtain the same error the second time (stderr: 'fatal: A branch named '_PD' already exists.').

I solved by adding this two lines to the script. It works, but it is a workaround ;-)
repo = git.Repo(GIT_REPOSITORY)
repo.git.checkout('master')

If it can be useful, I created a sample repository to test this feature: https://github.com/davidetaibi/PyDrillerTest. In the repository, I added one file per commit (1.txt first commit, 2.txt in the second commit, ...)  

Thank you
Davide

**Comment by ishepard** [comment]
Hello @davidetaibi! Glad that it helped!
It doesn't work if you don't call **git.reset()** at the end of the study (or after each **git checkout**). The idea is that when you run PyDriller, the repository should be in a clean state, not in some strange branch. See this [test](https://github.com/ishepard/pydriller/blob/aee50f80543ec27bc5d4d490620602bc87fa6794/tests/test_git_repository.py#L118). I can call multiple times this test, with no errors: the reason is that I call **git reset**, that means checkout the master branch. You don't have to do it every commit, but at least at the end of the study so that the next time PyDriller will start, will start from the master branch :) 

Thanks!
