### ISSUE TITLE
Getting ImportError while importing the RepositoryMining class

### ISSUE THREAD

**Issue by rayhanramin** [ishepard/pydriller#275]
I am trying to iterate over the commits of a github repository using pydriller. I am trying to use the **RepositoryMining** class for this purpose. But I am getting an ImportError provided below;

![importerror](https://github.com/ishepard/pydriller/assets/55429573/fd527e72-8f21-45bd-ab85-9e50e05c2911)
**OS Version:**
 Windows/MacOS

**Comment by ishepard** [comment]
Hi @rayhanramin!
`RepositoryMining` is an old class that doesn't exist anymore. The new name is `Repository`.

For more info you can reference the docs: [pydriller.readthedocs.io/en/latest/](http://pydriller.readthedocs.io/en/latest/)
