### ISSUE TITLE
Is there a way to analyze the diff between just two commits?

### ISSUE THREAD

**Issue by a-y-f** [ishepard/pydriller#278]
Imagine there is a commit list `[A, B, ..., Z]`, I want to extract the changed functions using diff between commit A and Z.
Like using `git diff A Z `, then extract the changed methods from diff.

Now I need to traverse all commits in `[A, B, ..., Z]`, then union the result.

**Comment by pyth0n1c** [comment]
I would also be interested in this feature - a diff between two commits (and similarly between the heads of two branches).

**Comment by ishepard** [comment]
Achieving this shouldn't be too hard, we just need to create a `diff` function inside `git.py` that accepts 2 commits.

If anyone would like to work on it, feel free to do it.
