### ISSUE TITLE
[Bug] Version 2.5.1 is not tagged in this repository

### ISSUE THREAD

**Issue by jtamagnan-delphix** [ishepard/pydriller#282]
**Describe the bug**

This is a relatively small issue but it should also be a simple issue to fix. A new version (2.5.1) of pydriller is available in PyPi but the release is not tagged here. Having the tags in the repository match the released packages makes it easier for consumers to compare changes between versions.

By the way thanks for this great packages! We've certainly found it useful

**Comment by ishepard** [comment]
You are so right, I completely forgot 😄 
Just did it. thanks!

**Comment by jtamagnan-delphix** [comment]
Thanks for the super quick fix and again for the helpful package! :tada:
