### ISSUE TITLE
parse_diff() yields wrong results for files ending without newline

### ISSUE THREAD

**Issue by gotec** [ishepard/pydriller#32]
If a file ends without a newline git represents this with the additional line

> \ No newline at end of file

in corresponding diffs. These lines are not parsed correctly in the `parse_diff()` function.

**Comment by ishepard** [comment]
Hi @gotec! Thank you for catching this. Can you please give me an example? A project, a commit and a file to check. What does my `parse_diff()` function returns?

Thanks!

**Comment by gotec** [comment]
Hi @ishepard. I have created a pull request including example and test and potential fix.

While writing the fix I realised that there might be an additional issue in case context lines in the diff read `\ No newline at end of file` for whatever reason. To prevent this, it might be beneficial to disable context lines in diffs outright if this does not cause any additional issues.

**Comment by ishepard** [comment]
> Hi @ishepard. I have created a pull request including example, test and potential fix.

Thanks I just saw it, cool!! Gonna check it now

> While writing the fix I realised that there might be an additional issue in case context lines in the diff read \ No newline at end of file for whatever reason. To prevent this, it might be beneficial to disable context lines in diffs outright if this does not cause any other issues.

I don't think that this will ever happen :) Anyway, the same problem would apply if the the line starts with `@@`..for now, I will just assume this doesn't happen. If people will complain, I will change it. 

Thanks!!

**Comment by gotec** [comment]
Yeah, I thought the same. Still wanted to let you know :)

**Comment by ishepard** [comment]
Awesome! Gonna release the update this afternoon after lunch.

Thank you again! Cheers
