### ISSUE TITLE
Use git-hyper-blame to improve SZZ results

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#46]
SZZ can blame the wrong commit when there are large formatting changes.

https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html can help with this, skipping large meaningless formatting changes (for projects that do have an up to date .git-blame-ignore-revs). Possibly, it would also be nice to be allowed to pass a set of commits to skip in addition to those listed in .git-blame-ignore-revs.

**Comment by ishepard** [comment]
Ciao @marco-c! 
If I understood correctly, it seems that if between the "culprit" commit and the fix commit there is another commit with big changes (such as mass reformatting or renaming), then the normal blame would pick up this big commit as the "culprit". What you would like to have instead is the real "culprit" commit. 

The only problem I see with your approach is that _git hyper-blame_ is not included in the normal version of Git (maybe in the future?), and installing Chromium depot_tools is probably not good (and necessary) for the users. Do you think this could be achieved using normal blames instead? 

What I was thinking is to add a check for the _buggy_commit_ to see if it contains more than X modifications (than it's probably a mass reformatting or renaming). Or we can even  pass a set of commits to skip, and we check whether _buggy_commit_ is in those.

**Comment by marco-c** [comment]
> If I understood correctly, it seems that if between the "culprit" commit and the fix commit there is another commit with big changes (such as mass reformatting or renaming), then the normal blame would pick up this big commit as the "culprit". What you would like to have instead is the real "culprit" commit.

Exactly!

> The only problem I see with your approach is that git hyper-blame is not included in the normal version of Git (maybe in the future?), and installing Chromium depot_tools is probably not good (and necessary) for the users. Do you think this could be achieved using normal blames instead?

What if it was optional? Use git-hyper-blame if available, resort to normal git blame otherwise.

> We can even pass a set of commits to skip, and we check whether buggy_commit is in those.

This solution would be better than the status quo, the only problem is that you wouldn't be able to go look behind the reformatting change. You won't wrongly blame the reformatting change, but you also won't be able to blame the actual culprit which is older than the formatting change.

**Comment by ishepard** [comment]
Yep I see. Sure, it looks good to me then. Could you be available to create a PR with the new feature? 
I was thinking to add a new parameter `smart=True` to the function to use git-hyper-blame, `False` for the normal git blame instead.
