### ISSUE TITLE
New commit filter "only_modifications_without_file_types" 

### ISSUE THREAD

**Issue by RafaelFazzolino** [ishepard/pydriller#50]
**I would like to be able to filter commits that modify files that do not have certain formats..**
I am interested in analyzing flow of commits taking into account certain format of the modified files. For example: I want to filter commits that modify '_.java_' format files (we already did it with '**only_modifications_with_file_types**'), however, I would also like to get all commits that do not modify '_.java_' files.

**Example of solution**
I would like to get a new commit filter, like: only_modifications_without_file_types = ['.java', '.c'], getting all commits that do not modify any '_.java_' files and any '_.c_' files.

**Additional context**

Filtering commits: https://pydriller.readthedocs.io/en/latest/configuration.html#filtering-commits
We need to add a new filter here with the described behavior.

**Comment by RafaelFazzolino** [comment]
I knew the tool a little while ago, but I loved it! I want to help in the evolution of it!
I'm currently a little busy, but as soon as I can relieve, I can work on this issue if it has not been fixed yet.

Thank you!

**Comment by ishepard** [comment]
hi @RafaelFazzolino! Thanks for opening the issue! I see your point, you'd like to get all the commits the did **not** modify a certain file type...like all the commits that did not touch source code. Make sense to me!

It shouldn't be too difficult, you can check the code of the filter "**only_modifications_with_file_types**", and do something similar. I will wait for your PR then 😄 
If you need help you can contact me!

Thanks!

**Comment by ishepard** [comment]
Closing the issue due to inactivity. Feel free to open it again
