### ISSUE TITLE
Only use hyper-blame when useful

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#52]
Right now, when hyper-blame is available, we always prefer it to normal blame.
In practice, we should use it only when useful (that is, when the user passes a path to a file containing hashes to ignore, or when the repository contains a default ignore file), as it can slow down blaming.

**Comment by ishepard** [comment]
This seems indeed a good idea. I can work on this since it's a trivial change. Thanks!

**Comment by ishepard** [comment]
Last release fixed this issue! Thank you!
