### ISSUE TITLE
I cannot use pydriller traverse_commits() method on detached repository

### ISSUE THREAD

**Issue by Vox1984** [ishepard/pydriller#55]
**Describe the bug**
I cannot use pydriller traverse_commits() method  from RepositoryMining class on detached repository, for other repositories it works fine. (I am intending to use it for enforcing some rules on commits, and I am doing it on detached branch).

**To Reproduce**
```
from pydriller import RepositoryMining
import calculateChanges as c

repo = "/home/repo"
lista = list(RepositoryMining(repo).traverse_commits())
```

Results in an exception:
```
/home/user/.local/lib/python3.6/site-packages/git/refs/symbolic.py", line 275, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'e12532b37ffe6d67140841a0a918c8b3744a01ae'
```

**OS Version:**
Python 3.6.9
Ubuntu 18.04.3 LTS

**Dummy Workaround:**
git_repository.py
```
    def _discover_main_branch(self, repo):
        if self.main_branch is None:
            self.main_branch = "dummy"
        else:
            self.main_branch = repo.active_branch.name
```

**Comment by ishepard** [comment]
Hi @Vox1984, thank you for opening the issue. I just tried myself and indeed it doesn't work.
I will fix it soon. 

On a side note, the problem will persist if you do checkouts or ask whether the commit is in the main branch (`commit.in_main_branch`). So my suggestion is to use start pydriller in a clean state, then use `GitRepository.checkout(commit_hash)` to checkout the commit, and then analyze the commit. Finally, you can use `GitRepository.reset()` to reset the repo. 

Thanks!

**Comment by Vox1984** [comment]
Hi @ishepard , thank you for fixing it so quickly!, I am amazed.
I have tested your change it and it works fine.

Thanks a lot!
