### ISSUE TITLE
UnicodeDecodeError while reading some commits

### ISSUE THREAD

**Issue by gotec** [ishepard/pydriller#58]
**Describe the bug**
When reading certain commits (likely containing non utf8 characters), the commit object breaks. A `UnicodeDecodeError` error is thrown when trying to access most properties. For details see the example below.

**To Reproduce**
E.g. commit 13e644bb36a0b1f3ef0c2091ab648978d18f369d in https://github.com/gentoo/gentoo.

```
import pydriller
import git

repo_url = 'https://github.com/gentoo/gentoo.git'
local_directory = '/tmp'
repo_name = 'gentoo'

git.Git(local_directory).clone(repo_url)

git_repo = pydriller.GitRepository(local_directory + '/' + repo_name)
commit = git_repo.get_commit('13e644bb36a0b1f3ef0c2091ab648978d18f369d')

commit.author_date
```

**OS Version:**
Ubuntu 19.04

**Comment by ishepard** [comment]
hi @gotec ! Thanks for finding this. 
Indeed, it seems that for some reason GitPython can not decode the date of the commit.
This code fails:
```
from git import Repo, Commit

gr = Repo('/tmp/gentoo')
c = gr.commit('13e644bb36a0b1f3ef0c2091ab648978d18f369d')

print(c.committed_datetime)
```
I am gonna open an issue on GitPtyhon to check why this happens.

**Comment by gotec** [comment]
hi @ishepard thanks for looking into this.

**Comment by ishepard** [comment]
I am gonna close the issue since my fix in GitPython has been merged. Thank you again!

**Comment by gotec** [comment]
Thanks again for looking into this. In this case I look forward to the next release of gitpython. However, I'm even more excited regarding your transition to pygit2!
Cheers
