### ISSUE TITLE
Implement histogram algorithm for diff

### ISSUE THREAD

**Issue by yusufsn** [ishepard/pydriller#59]
**Problems**
The `diff` utility calculates and displays the differences between two files, and is typically used to investigate the changes between two versions of the same file. Git offers four `diff` algorithms, namely, _Myers_, _Minimal_, _Patience_, and _Histogram_. Without an identifying algorithm, _Myers_ is used as the default algorithm. 
In textual differencing, all `diff` algorithms are computationally correct in generating the `diff` outputs. However, the `diff` outputs are sometimes different due to different `diff` algorithms. Different `diff` algorithms might identify different change hunks, that is, a list of program statements deleted or added contiguously, separated by at least one line of unchanged context. We expect that a set of changing operations done by developers can be represented by change hunks. However, there can be inappropriate identifications of change hunks.

**Recommendation**
Based on this paper, the authors investigated the impact of adopting different `diff` algorithms (_Myers_ and _Histogram_) on empirical studies and investigated which `diff` algorithm can provide better `diff` results that can be expected to recover the changing operations [[1]](https://doi.org/10.1007/s10664-019-09772-z). 
On the impact on code churn metrics and bug-introducing change identification in 24 Java projects, the result shows different code changes based on different `diff` algorithms. For patch application, the _Histogram_ is more suitable than _Myers_ for providing the changes of code.
Therefore, we recommend using the _Histogram_ algorithm in this tool for extracting code changes.

**References**
[1] Nugroho, Y. S., Hata, H. Matsumoto, K., How different are different diff algorithms in Git?, Empirical Software Engineering (2019). [Available online](https://doi.org/10.1007/s10664-019-09772-z)

**Comment by ishepard** [comment]
Hi @yusufsn ! Thank you for this, and congrats for the paper! I will have a look at it soon

**Comment by ishepard** [comment]
So, I read your paper, very interesting work! I was actually not familiar with these algorithms, I learnt something new of `git diff`, thanks! :) 

As for the change: many people relies on the `git diff` functionality of pydriller, and I am not feeling comfortable in changing the algorithm right away. I can imagine a scenario in which a researcher wants to check if the output of pydriller is correct, and then it runs `git diff` from the terminal, resulting in 2 different outputs. 

However, I think it could be a nice "flag" that we can add (hence leaving the choice of whether to choose the "normal" diff to the user). Would you available in implementing this feature and creating a PR? 

I was thinking to pass this configuration when creating the Commit object (see [line](https://github.com/ishepard/pydriller/blob/e7f51e7e48f9df729c6d808c9b5c409167a3c84b/pydriller/git_repository.py#L133)). And then, in the Commit object, when we ask for the diff, you just have to pass the "flag". 

If you need help just write me :)

**Comment by yusufsn** [comment]
I think a "flag" is a good idea. So that can make us select one of the available `diff` algorithms based on our goals.
But it is possible that most people still don't know the differences between those 4 `diff` algorithms (or at least 2: __Myers__ and __Histogram__). So, how to explain them in the tool?

**Comment by ishepard** [comment]
I understand your concern of getting people to know the 4 diff algorithms, however doing this through a tool is really difficult.
We can of course write it in the documentation, and we can point to your paper. Would this work for you?

**Comment by yusufsn** [comment]
I agree with you to write the description of each algorithm in the documentation. 
However, can you add those diff algorithms as a choice for users (at least _Myers_ and _Histogram_) in the tool?

**Comment by ishepard** [comment]
Mmm I don’t know if I understood The question correctly. My plan was to add this option as a flag, and explain this flag in the doc. 

Is this what you mean?

**Comment by yusufsn** [comment]
Yes, that's what I mean. Great!!!

**Comment by ishepard** [comment]
Hi @yusufsn! In the PR #64 I implemented the histogram diff. Now it's an option of `RepositoryMining` that you can set.
When you have time, could you please update the documentation? You can also put the link to your paper. 

Thanks!!

**Comment by yusufsn** [comment]
I sent a pull request to update the documentation.

Thank you.
