### ISSUE TITLE
Issues with filtering commits by file type

### ISSUE THREAD

**Issue by s0nata** [ishepard/pydriller#60]
**Describe the bug**
Filtering commits by file type modified seems to be not really working. Please see the script below for a MWE. Using filtering as in examples in the [docs](https://pydriller.readthedocs.io/en/latest/configuration.html).

**To Reproduce**
```
from pydriller import RepositoryMining

repo    = "https://github.com/jgrapht/jgrapht.git"
commits = [
    "0c62b9bea6ac0caeb6bc520d87708bceca0054dc", # README.html
    "0eec89d7d76077b485851c80e8f4e78e2d1e8cbf", # build.xml, package.html
    "0f3a10c6ea5258c0add31f2c1eb0ac64b015315a"  # README.html
]

for commit in RepositoryMining(repo,only_modifications_with_file_types=['.java'],only_commits=commits).traverse_commits():
    print(commit.hash)
    for modification in commit.modifications:
        if modification.filename[-4:] != 'java':
            print(modification.filename)
```

The output for me is:

```
$ python3 bug.py
0eec89d7d76077b485851c80e8f4e78e2d1e8cbf
build.xml
package.html
0f3a10c6ea5258c0add31f2c1eb0ac64b015315a
README.html
0c62b9bea6ac0caeb6bc520d87708bceca0054dc
README.html
```

**OS Version:**
Linux

My python installation is:
```
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
```

**Comment by ishepard** [comment]
Hi @s0nata ! Thank you for spotting this. 
My guess is that the double filter is not working, for some reason. 

I will have a look at it.

**Comment by ishepard** [comment]
Ok, so I checked and it's correct.
The reason is that in those commits there are `java` files.

Note that the filter is not exclusive: it doesn't mean "only commits that modified ONLY java files", but commits that "modified at least 1 java file". I will clarify this in the docs as well, since it's not clear.

**Comment by s0nata** [comment]
@ishepard OK, I see, thanks! Should I close this issue now, or you'll do it later with the fix in the docs?

**Comment by ishepard** [comment]
Perfect! :)

I will close it thanks!
