### ISSUE TITLE
filtering out commits with whitespace-only changes

### ISSUE THREAD

**Issue by s0nata** [ishepard/pydriller#61]
**Is your feature request related to a problem? Please describe.**
How hard would it be to add an option to include/exclude whitespace changes in diffs? More specifically, if a file modification in a commit only contains whitespace formatting changes.

**Describe the solution you'd like**
Maybe some commit filtering parameter like `only_modifications_nowhitespace=true/false` for the `RepositoryMining` class?

**Additional context**
Example: changes in file `Subgraph.java` in the commit [0ad4e7aa](https://github.com/jgrapht/jgrapht/commit/0ad4e7aa4cfa8aa6a1084840647777d1fbca3d33) are purely whitespace. If I do the `git diff` manually, the following two commands produce different results and the second case this file is not included in the diff:

```
$ git diff e07df84 0ad4e7aa | grep Subgraph
diff --git a/src/org/_3pq/jgrapht/graph/Subgraph.java b/src/org/_3pq/jgrapht/graph/Subgraph.java
--- a/src/org/_3pq/jgrapht/graph/Subgraph.java
+++ b/src/org/_3pq/jgrapht/graph/Subgraph.java
@@ -132,8 +132,8 @@ public class Subgraph extends AbstractGraph implements Serializable {
      * Creates a new Subgraph.

$ git diff -w e07df84 0ad4e7aa | grep Subgraph
```

**Comment by ishepard** [comment]
Hi @s0nata! 
You're right, in some cases indeed it could be useful to just skip those lines. Note however that the default behaviour of Pydriller should be to "mimic" Git. By default Git reports those lines, so I would leave it like that.

However, as you suggested, it can be a setting of RepositoryMining.

Would you be available to implement this feature?

Thanks!

**Comment by s0nata** [comment]
@ishepard I'm afraid, no - not a python programmer, that is why I was initially asking whether implementing this functionality is hard or not :-)

**Comment by ishepard** [comment]
@s0nata ok no worries then, I will implement it soon 😄
