### ISSUE TITLE
Use --histogram for git blame too

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#69]
https://link.springer.com/article/10.1007/s10664-019-09772-z reports better results for SZZ when using "--histogram".
Right now pydriller uses it for getting modifications, it might be useful to use it for blaming too.

**Comment by ishepard** [comment]
Hi @marco-c !

Yes you're right. We could do it automatically to be honest..that function is mainly used by researchers to get the buggy commits, hence if we have proofs that using "--histogram" produces better results, I would say that we can put it by default.

**Comment by ishepard** [comment]
Closing this issue. If someone wants to work on it feel free to re-open it.
