### ISSUE TITLE
Use --ignore-revs-file instead of hyper-blame

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#70]
It looks like "hyper blame" is now included in git itself (see https://stackoverflow.com/a/57129540/5769903 for details).

It might be beneficial to switch to this instead of having a custom implementation. It also has some additional features, e.g. "unblamable" lines.

**Comment by ishepard** [comment]
Hey marco,
thanks for getting this. It's wonderful news 😄 amazing, so I can remove our implementation of hyperblame

**Comment by marco-c** [comment]
The current `test_get_commits_last_modified_lines_hyper_blame_ignore_hash` is failing when using --ignore-revs-file instead of hyper-blame.

```
marco@marco-Dell-XPS ~/Documenti/workspace/pydriller/test-repos/test5 (master)$ git blame --ignore-rev 540c7f31c18664a38190fafb6721b5174ff4a166 e6d3b38a9ef683e8184eac10a0471075c2808bbd^ B.java
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 1) class Arquivo {
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 2)   void a() {
6de55acc (ishepard 2018-06-05 17:16:44 +0200 3)    a();
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 4)   }
540c7f31 (ishepard 2018-06-05 17:16:21 +0200 5)   inserting a bug
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 6) }
```

540c7f31 is not skipped despite being in the ignore list. This is actually because the line is "unblamable":
```
marco@marco-Dell-XPS ~/Documenti/workspace/pydriller/test-repos/test5 (master)$ git -c blame.markUnblamableLines=true blame --ignore-rev 540c7f31c18664a38190fafb6721b5174ff4a166 6de55acc8f0eafac3b7f98ddb1817ae3ea9e88c0 B.java
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 1) class Arquivo {
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 2)   void a() {
6de55acc (ishepard 2018-06-05 17:16:44 +0200 3)    a();
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 4)   }
*540c7f3 (ishepard 2018-06-05 17:16:21 +0200 5)   inserting a bug
^22505e9 (ishepard 2018-06-05 17:15:39 +0200 6) }
```

Indeed, the test is not really reflective of reality because the skipped commit was not really a meaningless commit. We should write a more meaningful one.

When we start using --ignore-revs-file, with the addition of "unblamable" lines support, we should have even better results for blame.
