### ISSUE TITLE
Ability to provide a directory to store clone of remote repo instead of using a temporary directory

### ISSUE THREAD

**Issue by jphgoodwin** [ishepard/pydriller#71]
**Problem**
For my work I need to access the other files in the repo that weren't altered by the commit. If I'm using a remote repo then the clone is stored in a temp folder and is inaccessible.

**Potential solution**
I need the ability to access the cloned repo when iterating over commits. As I see it there are two main ways of doing this: first you could make the temp folder accessible (the best approach to this is not clear to me), and second you could add a new configuration option through which the user could specify a location for the cloned repo. The second option would leave the task of managing the destruction of the cloned repo to the user, giving them the option to persist it as long as they deem necessary. I am in favor of the second option.

I was initially thinking to hack something together for my own purposes, but the thought occurred to me that this might be something that would be useful to other users and so I'm presenting it as a feature request. Feel free to assign this to me.

**Comment by ishepard** [comment]
Hi @jphgoodwin! 
Yes indeed, currently it's not possible.
If you want it though, you could clone it by yourself (using GitPython, or Git manually) and then run Pydriller.

However, what you're suggesting might be a good option. We can have a parameter in RepositoryMining, something like `clone_repo_to` that, if set, will clone the repo in that directory.

Would you be available to create the PR? 😄 
Thank you!

**Comment by jphgoodwin** [comment]
Yes, I'll look at implementing it and submitting a pull request.
