### ISSUE TITLE
commits from "git log --all"

### ISSUE THREAD

**Issue by rafed123** [ishepard/pydriller#72]
By default RepositoryMining().traverse_commits()  shows the commits can be seen by running "git log". Is there a way to see all the commits? i.e "git log --all"

If not, it'd be really useful for me if that feature was available. :/

**Comment by ishepard** [comment]
Hi @rafed123! 
I think it's definitely possible, it can be an option of RepositoryMining. 
Would you be available to create this feature?

Thank you!

**Comment by rafed123** [comment]
I could give it a try. Gonna need a bit of time though.

**Comment by ishepard** [comment]
Yes of course, take the time you need! If you need help just comment on this issue, or open the PR and I will comment there.

Thanks!

**Comment by wangpeipei90** [comment]
From what I can see, 
> The --all option does not tell git log to display all commits. It asks for the logs of all refs, basically your branches and tags.

There might be a misunderstanding about "git log --all" does. 
See the discussion on [StackOverflow post](https://stackoverflow.com/questions/29756637/what-does-git-log-all-do)

**Comment by dctanner** [comment]
I think you can do this today by using the option `only_in_branch='--all'`, even though it's a little bit of a hack.

**Comment by ishepard** [comment]
@dctanner that's true, but after searching a bit for what `git log --all` does, it seems it's not that useful. I will close this issue and re-open it if needed.

**Comment by 50417** [comment]
The behavior that it only gets commits from current branch needs to be clearly documented somewhere. Reading the Pydriller PDF lead me to believe otherwise 

Whats a quick workaround to get commit from all branches of a project? I might be able to give it a shot. :)
