### ISSUE TITLE
Get tag of file

### ISSUE THREAD

**Issue by HolgerNie** [ishepard/pydriller#78]
Is there a way to get the tag of a file in the repo? I can get the author but not the tag.

Holger

**Comment by ishepard** [comment]
Hi Holger! 
I am not familiar with the tag of a file. What do you mean by that?

**Comment by HolgerNie** [comment]
Hello,
we're about to convert CVS to GIT. With CVS you could also tag single files. I guess we have to treat this differently in GIT.
Thanks for the quick feedback Greetings Holger

**Comment by ishepard** [comment]
Ok perfect 😄 Feel free to contact me if you have other questions!
