### ISSUE TITLE
Need to test reversed_order=True with (from_commit=None, to_commit=sha) and (from_commit=sha, to_commit=None)

### ISSUE THREAD

**Issue by stefanodallapalma** [ishepard/pydriller#85]
The last four commits of pydriller are (from oldest to newest):

```
13c29c9773c599094caadba0b04ba99aebb1cce5
14535c53e82505c7a4c1c6c96ff7afc43a0849d9
6ae8b9dba47cf79ed10ba30aaf3ac58dc21adcf1
07099286e8a06680038d6c1ac9ba1ebb12a1406e
```

When testing the following code:

```
for commit in RepositoryMining('https://github.com/ishepard/pydriller', from_commit='13c29c9773c599094caadba0b04ba99aebb1cce5', to_commit=None, reversed_order=True).traverse_commits():
    print(commit.hash)
```

I **expect** the following:

```
07099286e8a06680038d6c1ac9ba1ebb12a1406e (latest)
6ae8b9dba47cf79ed10ba30aaf3ac58dc21adcf1 (latest - 1)
14535c53e82505c7a4c1c6c96ff7afc43a0849d9 (latest - 2)
13c29c9773c599094caadba0b04ba99aebb1cce5 (latest - 3)
```

but I **obtain** all the commits from the first to ```from_commit```:

```
13c29c9773c599094caadba0b04ba99aebb1cce5 (from_commit = latest - 3)
386b6eecd23c9fc5222624b0898aa7ee05121765
d519d9ca5a22686ed104f20a6294ed575096612f
f470ff1fc7f25b03cb4b72742d052176ab80b05f
...
71e053f61fc5d31b3e31eccd9c79df27c31279bf
90ca34ebfe69629cb7f186a1582fc38a73cc572e
fdf671856b260aca058e6595a96a7a0fba05454b
ab36bf45859a210b0eae14e17683f31d19eea041 (1st commit)
```

The opposite happens when ```from_commit=None```. For example, with

```
for commit in RepositoryMining('https://github.com/ishepard/pydriller', from_commit=None, to_commit='71e053f61fc5d31b3e31eccd9c79df27c31279bf' , reversed_order=True).traverse_commits():
    print(commit.hash)
```

I **expect** the following:

```
71e053f61fc5d31b3e31eccd9c79df27c31279bf (4th commit)
90ca34ebfe69629cb7f186a1582fc38a73cc572e
fdf671856b260aca058e6595a96a7a0fba05454b
ab36bf45859a210b0eae14e17683f31d19eea041 (1st commit)
```

and **obtain** all the commits from the latest to ```to_commit```:

```
07099286e8a06680038d6c1ac9ba1ebb12a1406e (latest commit)
6ae8b9dba47cf79ed10ba30aaf3ac58dc21adcf1 (latest - 1)
14535c53e82505c7a4c1c6c96ff7afc43a0849d9 (latest - 2)
13c29c9773c599094caadba0b04ba99aebb1cce5 (latest - 3)
...
2437f7bb5659a342b8d74c169d175604170395ae (7th commit)
f8b713a9f5e4620abbbc84f45493352fc046b5e0 (6th commit)
205f6fb09734667b0c1842fd3c317013640189ce (5th commit)
71e053f61fc5d31b3e31eccd9c79df27c31279bf (to_commit = 4th commit)
```

**NOTE:** This behavior shows only when ```reversed_order = True```. Furthermore, passing both ```from_commit``` and  ```to_commit``` (or setting both to ```None```) works as intended. 

**Version**: latest version installed from current master -> commit ```07099286e8a06680038d6c1ac9ba1ebb12a1406e```

**Comment by ishepard** [comment]
Hi Stefano!
The current implementation is correct. If there are these commits:
```
A
B
C
D
E
```
normally pydriller would return them like: `E D C B A`. 
If you ask them in reverse order, then it would return them like: `A B C D E`.
If you know add `from_commit=B`, then it will return `B C D E`. 
This is what's happening in your case: you are asking, in reverse order, the commits from `13c29c9`. That are all the commits in pydriller, starting from `13c29c9`. Hope this helps! 😃

**Comment by stefanodallapalma** [comment]
Hi Davide!
Yes, indeed, this helps. To get what I expect I need to call 

```
from_commit=None, 
to_commit='13c29c9773c599094caadba0b04ba99aebb1cce5', 
reversed_order=True
```

However, honestly, I think that some examples in the doc could help to clarify.
I am noticing that I have intended the behavior in a slightly different way wrt you, that is, if there are these commits:

```
A (newest)
B
C
D
E (oldest)
``` 
normally pydriller would return them like: ```E D C B A```.

My understanding was that when setting, say, ```from_commit=C, reverse_order=True```, pydriller first filters out ```E D``` and then reverse the order, thus getting ```B A```.

From your comment, instead, I am now understanding that it first reverses the order, from ```E D C B A``` to ```A B C D E``` and then filters out ```A B``` (because ```from_commit=C```).

As a user of the tool, IMHO we should update the doc specifying this order to avoid similar misunderstandings.

**Comment by ishepard** [comment]
Indeed, makes sense to me! I will update the docs.
Thanks!

**Comment by stefanodallapalma** [comment]
Ciao @ishepard,

given ```from_commit = 'hash'```  and ```to_commit=None```, can you confirm whether pydriller

- selects first the commits from ```hash``` to the latest, and then reverses the order of the resulting hashes, or

- reverses the whole story first (from the latest commit to the first commit), and then select the commits starting from ```hash```?

I was running some experiments (based on https://github.com/ishepard/pydriller/issues/85#issuecomment-584547935) which seemed fine, but now, performing some tests with the new version I've noticed that the behaviour is different again and that the issue I raised here is no longer an issue, in the sense that the expected results are now correct.

**Comment by ishepard** [comment]
Hi @stefanodallapalma,
indeed, I now changed the filtering in Pydriller and I use git filter "--reverse" to reverse the commits.
I don't know how git does it, but what I use to select the commits and/or reverse is explained [here](https://git-scm.com/docs/git-rev-list).
