### ISSUE TITLE
to_commit and from_commit no longer support HEAD

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#90]
There have been some recent changes to traverse_commits options that made some of my code break. I've tried quickly fiddling with the options, but it didn't help.

In the end, after debugging pydriller's code, I found out that the problem is that passing HEAD to either to_commit or from_commit breaks a lot of pydriller's assumptions.

I think HEAD (and similar references) should be supported, or clear errors should be spit out.

**Comment by ishepard** [comment]
Hi @marco-c!
Could you provide me with an example of code that doesn't work? 
Thanks!

**Comment by marco-c** [comment]
```Python
commits = list(RepositoryMining(".", single="HEAD").traverse_commits())
assert len(commits) == 1
```

**Comment by ishepard** [comment]
thank you! 
I will try it out. 

I wonder what change I made to break that 😕

**Comment by marco-c** [comment]
Another case, not sure if it's the same underlying bug, but it can probably be fixed similarly:
```Python
commits = list(RepositoryMining(".", from_commit=A_COMMIT_HASH, to_commit="HEAD", reversed_order=True).traverse_commits())
# the list should only contain commits between A_COMMIT_HASH and HEAD, in inverse chronological order.
```

**Comment by ishepard** [comment]
the thing is that the code you posted should have never worked 😄 
for those filters, what I do is: 

```
if commit.hash == self.get('single'):
```
so this will be translated to:

```
if "9571e55723aeef1fe1f3d080c5618c1f6899d934" == "HEAD":
```
which is of course wrong. I will work on a fix soon.

Thanks!

**Comment by marco-c** [comment]
`commits = list(RepositoryMining(".", single="HEAD").traverse_commits())` was actually `commits = list(RepositoryMining(".", from_commit="HEAD", to_commit="HEAD", reversed_order=True).traverse_commits())` in the code; it worked with pydriller 1.9.2.
