### ISSUE TITLE
Recent changes to traverse_commits broke existing code without warnings

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#91]
`RepositoryMining(".", from_commit=older_commit, to_commit=newer_commit, reversed_order=True).traverse_commits()` used to work.
Now, it returns all commits in the repo, without printing any warning.

Instead, you have to use `RepositoryMining(".", from_commit=newer_commit, to_commit=older_commit, reversed_order=True).traverse_commits()`.

**Comment by ishepard** [comment]
yes indeed you're right. The last release inserted this bug.

However, I already fixed it. I just have to publish the new release. 

I will do it with the fix of the other issue (which I have already done, I am testing it right now)

**Comment by ishepard** [comment]
hey Marco,
I just released version 1.11.1, with the patches.

Thanks again!
