### ISSUE TITLE
Results are not consistent between traverse_commits and git log --reverse

### ISSUE THREAD

**Issue by marco-c** [ishepard/pydriller#93]
`git log d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0^..ed0d83d64365762361bcc491f72c33b272bc815f --reverse` shows:
```
d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0
6c05c922e3dfb1a200e3db6318b5197b9d85c08c
```

Instead, with pydriller:
```
>>> commits = list(RepositoryMining(".", from_commit="d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0", to_commit="ed0d83d64365762361bcc491f72c33b272bc815f").traverse_commits())
>>> commits[0].hash
'd2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0'
>>> commits[1].hash
'ee1e094b81f0efa26c1bc570959b8981ae425488'
```

**Comment by marco-c** [comment]
With this repo: https://github.com/mozilla/gecko-dev.

**Comment by ishepard** [comment]
I just tried on a fake repo, and having commits:

A -> B -> C -> D
if I ask from B to D, I get B -> C -> D
if I ask from B to D in reverse order, I get D -> C -> B

Both are correct. 
What's the problem with your example?

(I am cloning gecko, though it's taking forever 😄). As soon as I finish cloning it, I will debug it

**Comment by marco-c** [comment]
>  What's the problem with your example?

They are not in the same order as git log. With git log, after d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 comes 6c05c922e3dfb1a200e3db6318b5197b9d85c08c; with pydriller after d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 comes ee1e094b81f0efa26c1bc570959b8981ae425488.

**Comment by ishepard** [comment]
mmm commit "ed0d83d64365762361bcc491f72c33b272bc815f" doesn't exist

```
> git show ed0d83d64365762361bcc491f72c33b272bc815f
fatal: bad object ed0d83d64365762361bcc491f72c33b272bc815f
```
so
```
for commit in RepositoryMining('/tmp/gecko-dev',
                               from_commit="d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0",
                               to_commit="ed0d83d64365762361bcc491f72c33b272bc815f").traverse_commits():
    print(commit.hash)
```
returns:
```
Traceback (most recent call last):
  File "/Users/dspadini/Documents/pydriller/tmp.py", line 399, in <module>
    to_commit="ed0d83d64365762361bcc491f72c33b272bc815f").traverse_commits():
  File "/Users/dspadini/Documents/pydriller/pydriller/repository_mining.py", line 153, in traverse_commits
    self._conf.sanity_check_filters()
  File "/Users/dspadini/Documents/pydriller/pydriller/utils/conf.py", line 73, in sanity_check_filters
    self.check_ending_commit()
  File "/Users/dspadini/Documents/pydriller/pydriller/utils/conf.py", line 169, in check_ending_commit
    self.get('to_commit')).hash)
  File "/Users/dspadini/Documents/pydriller/pydriller/git_repository.py", line 143, in get_commit
    gp_commit = self.repo.commit(commit_id)
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/repo/base.py", line 481, in commit
    return self.rev_parse(text_type(rev) + "^0")
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/repo/fun.py", line 213, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/repo/fun.py", line 150, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/objects/base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/cmd.py", line 1083, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/cmd.py", line 1072, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/Users/dspadini/Documents/pydriller/venv/lib/python3.7/site-packages/git/cmd.py", line 1036, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'ed0d83d64365762361bcc491f72c33b272bc815f' could not be resolved, git returned: b'ed0d83d64365762361bcc491f72c33b272bc815f missing'
```

**Comment by marco-c** [comment]
Sorry, it was a local commit, try using HEAD

**Comment by ishepard** [comment]
OK. Indeed you are correct. 
Pydriller returns 
```
d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0
ee1e094b81f0efa26c1bc570959b8981ae425488
77af789c1f05527e2fbe6fc89b77229bb6ebc38b
309ac043a07b02ee75539eadf5a29651e5df9f7d
...
```
while git returns:
```
d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0
6c05c922e3dfb1a200e3db6318b5197b9d85c08c
3cd17a373a725cb04dcedfc096889d9d34373cac
6d6aa4cc6680a1c36497ae8707eac0e3808f5932
...
```

The funny thing is that pydriller returns the commit `6c05c9` (and all the commits after) as commit number 6569 and so on. 

But I have some doubts that Pydriller is not correct.
Commit `6d6aa4` is of October 25. According to git, the next commit was `6c05c92` what was January 15. Mmmmm

**Comment by marco-c** [comment]
> Commit 6d6aa4 is of October 25. According to git, the next commit was 6c05c92 what was January 15. Mmmmm

ee1e094b81f0efa26c1bc570959b8981ae425488 is from 22 Nov, so it's the same here: there are surely other commits in chronological order that are between d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 and ee1e094b81f0efa26c1bc570959b8981ae425488.

We should probably:
1) Make sure they at least return the same commit hashes, even if not in the same order;
2) Figure out what is the order pydriller is returning (if it is not chronological);
3) Figure out what is the order git log is returning (since it does not appear to be chronological, at least not in commit timestamp order, even though the docs say it is: https://git-scm.com/docs/git-log#_commit_ordering);
4) explain pydriller's ordering in the documentation.

**Comment by marco-c** [comment]
NOTE: the gecko-dev repository is a mirror of a mercurial repository. In the Mercurial repository, d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 was committed on 25 Oct put landed on 14 Jan. The next commit landed was 5f7e7a33fb8bf165190240081b108f39ad254e11 committed on 13 Jan and landed on 14 Jan.

`git log d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0^..ed0d83d64365762361bcc491f72c33b272bc815f --reverse --first-parent`
or
`git log d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0^..ed0d83d64365762361bcc491f72c33b272bc815f --reverse 
--ancestry-path`
show 5f7e7a33fb8bf165190240081b108f39ad254e11 after d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0.

ee1e094b81f0efa26c1bc570959b8981ae425488 was landed a bit later, it's shown following d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 probably because of the merge history (and that's why --first-parent or --ancestry-path change the result).

This kind of explains the output of git log, even though I'm still not sure how it knows that d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 was landed on Jan 14.

**Comment by ishepard** [comment]
Yes indeed,
I know that `git log` orders the commit by commit date, while it shows the author date.

So this might explain why we obtain difference results. The mirror dates are a bit different.
I use `git show --pretty=fuller COMMITHASHHERE` to see both author date and committer date.

As you can see, commit `d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0` landed on the 25th Oct according to git. But you said it actually landed  on Jan 14. 

The commit after that (according to git) is `6c05c922e3dfb1a200e3db6318b5197b9d85c08c`, which landed on Jan 15th. 

However, commit `ee1e094b81f0efa26c1bc570959b8981ae425488` and the others have the committer date before, like in November.

**Comment by ishepard** [comment]
how can git understand that commit `d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0` landed on the 14th of January though I don't know. It's not reported anywhere. 

```
> git show --pretty=fuller d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0
commit d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0
Author:     Andi-Bogdan Postelnicu <bpostelnicu@mozilla.com>
AuthorDate: Fri Oct 25 08:21:07 2019 +0000
Commit:     Andi-Bogdan Postelnicu <bpostelnicu@mozilla.com>
CommitDate: Fri Oct 25 08:21:07 2019 +0000

    Bug 1590414 - For C++ static analysis cleanup the running scripts. r=marco

    Differential Revision: https://phabricator.services.mozilla.com/D50065

    --HG--
    extra : moz-landing-system : lando
```

**Comment by marco-c** [comment]
Probably git doesn't know that, but it doesn't only rely on the commit dates but also on the paths between the commits, so it knows that ee1e094b81f0efa26c1bc570959b8981ae425488 came before d2990dc0e788ccd43e89b04f5c2f9d5a16c1eec0 without looking at their dates.

**Comment by marco-c** [comment]
> We should probably:
> Make sure they at least return the same commit hashes, even if not in the same order;

They probably don't because `git log` shows fewer commits than pydriller, but that's OK as long as we understand the following.

> Figure out what is the order pydriller is returning (if it is not chronological);

I think this would still be useful to understand in order for us to document it, maybe we have to look at GitPython's source code.

> Figure out what is the order git log is returning (since it does not appear to be chronological, at least not in commit timestamp order, even though the docs say it is: https://git-scm.com/docs/git-log#_commit_ordering);

I think we have a reasonable understanding now, it doesn't only consider dates but also path between commits. With #94 we can make sure we have a good way to traverse commits from strange repos such as this one.

**Comment by marco-c** [comment]
@ishepard thanks for the fix!
